from __future__ import annotations

from datetime import datetime
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side


ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = ROOT / "artifacts" / "wise-assistant-layout-context.xlsx"


def make_rows(columns, items):
    return [dict(zip(columns, item)) for item in items]


README_COLUMNS = ["Field", "Value"]
README_ROWS = make_rows(
    README_COLUMNS,
    [
        (
            "Workbook purpose",
            "Structured UI context for Wise Assistant so it can answer where things are, what they mean, and what actions each major control performs inside pwise.",
        ),
        (
            "Scope",
            "Public auth pages, authenticated app shell, page switcher, primary screens, important overlays, and main action controls.",
        ),
        (
            "Navigation model",
            "The app uses a left sidebar for navigation. The sidebar footer contains the active page switcher and the user account menu. The topbar is mostly for opening the mobile menu.",
        ),
        (
            "Page-scoped screens",
            "Dashboard, Content Calendar, Analytics, Post Pool, and Upload are tied to the active page selected in Switch Page.",
        ),
        (
            "Messaging model",
            "Messaging has a left mode rail, a conversation list panel, and a conversation thread panel. Customer messaging and agent-to-agent chat are separate surfaces.",
        ),
        (
            "Best sheets for AI context",
            "Use '2_Screens' for page meaning, '3_Controls' for button location and behavior, and '4_Assistant Playbook' for direct user-guidance patterns.",
        ),
        (
            "Generated from",
            f"Codebase snapshot in {ROOT} on {datetime.now().astimezone().strftime('%Y-%m-%d %H:%M:%S %Z')}.",
        ),
    ],
)


NAVIGATION_COLUMNS = [
    "Label",
    "Route or Surface",
    "Group",
    "Layout Position",
    "Meaning",
    "Purpose",
    "Visible To",
    "Notes",
    "Source",
]
NAVIGATION_ROWS = make_rows(
    NAVIGATION_COLUMNS,
    [
        (
            "Dashboard",
            "/dashboard",
            "Workspace sidebar",
            "Left sidebar, upper navigation",
            "Overview screen for the currently active page.",
            "Shows posting health, automation state, and quick operational shortcuts.",
            "Users with Dashboard access",
            "Page-scoped screen.",
            "client/src/components/AppLayout.jsx; client/src/pages/Dashboard/DashboardPage.jsx",
        ),
        (
            "Content Calendar",
            "/content-calendar",
            "Workspace sidebar",
            "Left sidebar, upper navigation",
            "Monthly planning view for scheduled posts and content notes.",
            "Lets the user inspect dates, open a day planner, and create future posts.",
            "Users with Content Calendar access",
            "Page-scoped screen.",
            "client/src/components/AppLayout.jsx; client/src/pages/ContentCalendar/ContentCalendarPage.jsx",
        ),
        (
            "Analytics",
            "/analytics",
            "Workspace sidebar",
            "Left sidebar, upper navigation",
            "Performance reporting for the active page.",
            "Shows follower, reach, and engagement trends plus top content.",
            "Users with Analytics access",
            "Page-scoped screen.",
            "client/src/components/AppLayout.jsx; client/src/pages/Analytics/AnalyticsPage.jsx",
        ),
        (
            "Post Pool",
            "/post-pool",
            "Workspace sidebar",
            "Left sidebar, upper navigation",
            "Library of uploaded, scheduled, posted, and archived content.",
            "Central place to review, edit, delete, and inspect posts.",
            "Users with Post Pool access",
            "Page-scoped screen.",
            "client/src/components/AppLayout.jsx; client/src/pages/PostPool/PostPoolPage.jsx",
        ),
        (
            "Upload",
            "/upload",
            "Workspace sidebar",
            "Left sidebar, upper navigation",
            "Post creation screen.",
            "Creates text, image, video, or template-based posts for the active page.",
            "Users with Upload access",
            "Page-scoped screen.",
            "client/src/components/AppLayout.jsx; client/src/pages/UploadPost/UploadPostPage.jsx",
        ),
        (
            "Messaging",
            "/messages",
            "General sidebar",
            "Left sidebar, lower navigation",
            "Shared messaging workspace.",
            "Handles customer conversations and agent-to-agent chat.",
            "Users with Messaging access",
            "Not page-scoped in the same way as posting screens, but customer view can be filtered by page.",
            "client/src/components/AppLayout.jsx; client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Connections",
            "/connections",
            "General sidebar",
            "Left sidebar, lower navigation",
            "Teammate connection management.",
            "Controls who can message whom in the internal agent chat.",
            "Users with Connections access",
            "Sidebar badge shows pending incoming requests.",
            "client/src/components/AppLayout.jsx; client/src/pages/Connections/ConnectionsPage.jsx",
        ),
        (
            "Vault",
            "/vault",
            "General sidebar",
            "Left sidebar, lower navigation",
            "Shared file repository.",
            "Stores reusable images, videos, documents, and folders for the workspace.",
            "Users with Vault access",
            "Supports browsing, search, filtering, upload, preview, and download.",
            "client/src/components/AppLayout.jsx; client/src/pages/Vault/VaultPage.jsx",
        ),
        (
            "Logs",
            "/logs",
            "General sidebar",
            "Left sidebar, lower navigation",
            "Posting attempt history.",
            "Shows successes and failures from automated publishing runs.",
            "Users with Logs access",
            "Useful for troubleshooting posting issues.",
            "client/src/components/AppLayout.jsx; client/src/pages/Logs/LogsPage.jsx",
        ),
        (
            "Activity",
            "/activity",
            "General sidebar",
            "Left sidebar, lower navigation",
            "Audit trail of content-note and post actions.",
            "Shows who changed content and when.",
            "Users with Activity access",
            "Useful for accountability and history.",
            "client/src/components/AppLayout.jsx; client/src/pages/Activity/ActivityPage.jsx",
        ),
        (
            "Accounts",
            "/accounts",
            "General sidebar",
            "Left sidebar, lower navigation",
            "Admin account and invite management.",
            "Generates invite links and manages active/inactive users.",
            "Admins only",
            "Hidden from non-admin users.",
            "client/src/components/AppLayout.jsx; client/src/pages/Accounts/AccountsPage.jsx",
        ),
        (
            "Settings",
            "/settings",
            "General sidebar",
            "Left sidebar, lower navigation",
            "Operational settings and integrations.",
            "Controls posting behavior, connected pages, and video templates.",
            "Users with Settings access",
            "Some sections are admin-only or feature-flagged.",
            "client/src/components/AppLayout.jsx; client/src/pages/Settings/SettingsPage.jsx",
        ),
        (
            "Sidebar collapse",
            "Sidebar state toggle",
            "App shell utility",
            "Top of desktop sidebar",
            "Switches the sidebar between expanded and icon-only modes.",
            "Gives more content width on desktop.",
            "Authenticated users",
            "State is remembered in local storage.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Switch Page",
            "Switch Page modal trigger",
            "App shell utility",
            "Sidebar footer, page card",
            "Opens the page-switcher modal.",
            "Changes the active Facebook page context used by page-scoped screens.",
            "Authenticated users with at least one page",
            "Button label changes to 'Switching...' during page change.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Switch Page page rows",
            "Switch Page modal",
            "App shell utility",
            "Modal body overlay",
            "Selectable list of connected pages.",
            "Lets the user activate another connected page.",
            "Authenticated users with active pages",
            "Expired rows can expose an Update shortcut for admins.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Refresh page data",
            "Switch Page modal header action",
            "App shell utility",
            "Top-right of Switch Page modal header",
            "Refreshes page names and follower counts from Facebook.",
            "Keeps page metadata current and flags expired tokens.",
            "Authenticated users",
            "Failed refreshes mark pages as Expired.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Add page",
            "Switch Page modal footer action",
            "App shell utility",
            "Bottom of Switch Page modal",
            "Shortcut into page connection settings.",
            "Lets admins add another connected page.",
            "Admins only",
            "Links to Settings -> Facebook Pages.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Account menu button",
            "User menu trigger",
            "App shell utility",
            "Sidebar footer, below page switcher",
            "Opens the signed-in user menu.",
            "Gives access to profile, privacy policy, theme toggle, and logout.",
            "Authenticated users",
            "Also shows user identity details.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "User Profile",
            "/profile",
            "User menu",
            "Inside user menu overlay",
            "Account profile screen.",
            "Lets the user edit name/email and change avatar or password.",
            "Authenticated users",
            "Accessible from both menu header and menu item.",
            "client/src/components/AppLayout.jsx; client/src/pages/Profile/ProfilePage.jsx",
        ),
        (
            "Privacy Policy",
            "/privacy",
            "User menu / public link",
            "Inside user menu overlay and login screen footer",
            "Legal policy page.",
            "Explains data handling, storage, connected channels, and deletion.",
            "All users",
            "Public route.",
            "client/src/components/AppLayout.jsx; client/src/pages/Privacy/PrivacyPolicyPage.jsx",
        ),
        (
            "Theme toggle",
            "Light theme / Dark theme",
            "User menu",
            "Inside user menu overlay",
            "Changes the app theme.",
            "Lets the user switch between dark and light mode.",
            "Authenticated users",
            "Label flips based on current theme.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Logout",
            "User menu action",
            "User menu",
            "Bottom area of user menu overlay",
            "Signs the user out.",
            "Ends the authenticated session.",
            "Authenticated users",
            "Styled as a danger action.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Open menu",
            "Mobile nav trigger",
            "App shell utility",
            "Top-left of mobile topbar",
            "Opens the sidebar drawer on smaller screens.",
            "Makes navigation available on mobile layout.",
            "Authenticated users on narrow screens",
            "Desktop users mainly use the fixed sidebar instead.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Connect a page",
            "/settings",
            "Sidebar footer fallback",
            "Sidebar footer when no pages are connected",
            "Fallback shortcut for empty page state.",
            "Gives admins a path to connect their first page.",
            "Admins with zero connected pages",
            "Only shown when no pages exist.",
            "client/src/components/AppLayout.jsx",
        ),
    ],
)


SCREEN_COLUMNS = [
    "Screen",
    "Route or Surface",
    "Layout Pattern",
    "Purpose",
    "Primary Regions",
    "Primary Actions",
    "Visible To",
    "Depends On",
    "Source",
]
SCREEN_ROWS = make_rows(
    SCREEN_COLUMNS,
    [
        (
            "Login",
            "/login",
            "Centered auth card",
            "Signs existing users into pwise.",
            "Logo header, email/password form, footer links.",
            "Log in, open privacy policy.",
            "Public",
            "None",
            "client/src/pages/Login/LoginPage.jsx",
        ),
        (
            "Signup",
            "/signup?token=...",
            "Centered auth card",
            "Creates a new invited account.",
            "Invite validation state, account form, invalid-link fallback.",
            "Create account, return to login when invite is invalid.",
            "Public invite recipients",
            "Valid invite token",
            "client/src/pages/Signup/SignupPage.jsx",
        ),
        (
            "Privacy Policy",
            "/privacy",
            "Legal document page",
            "Explains app data practices, integrations, retention, and contact details.",
            "Document header, numbered sections, back link.",
            "Read policy, return to login.",
            "Public",
            "None",
            "client/src/pages/Privacy/PrivacyPolicyPage.jsx",
        ),
        (
            "App shell",
            "Authenticated frame",
            "Left sidebar + footer utilities + mobile topbar + routed content",
            "Provides consistent app navigation and page switching.",
            "Sidebar nav, page switcher, user menu, mobile menu, main content outlet.",
            "Navigate screens, switch active page, manage account.",
            "Authenticated users",
            "User permissions and active page",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Switch Page modal",
            "Overlay from sidebar footer",
            "Modal with list rows and admin footer action",
            "Lets the user pick the active page or refresh page metadata.",
            "Header action, page list, optional admin footer.",
            "Switch page, refresh pages, add page, update expired page.",
            "Authenticated users",
            "At least one connected page for switching",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Dashboard",
            "/dashboard",
            "Page head + stat cards + operational cards",
            "Overview of automated posting status for the active page.",
            "Title area, warning banner, stats grid, Automation card, Pipeline card.",
            "Upload post, edit settings, manage pool, view logs.",
            "Users with Dashboard access",
            "Active page",
            "client/src/pages/Dashboard/DashboardPage.jsx",
        ),
        (
            "Content Calendar",
            "/content-calendar",
            "Page head + single large calendar card",
            "Monthly planning surface for scheduled posts and planning notes.",
            "Calendar header, month grid, legend, day planner modal.",
            "Move between months, open a day, manage notes, create a post for a day.",
            "Users with Content Calendar access",
            "Active page",
            "client/src/pages/ContentCalendar/ContentCalendarPage.jsx; client/src/components/CalendarMonth.jsx",
        ),
        (
            "Day planner modal",
            "Calendar day overlay",
            "Modal with top actions, scheduled posts list, and notes list",
            "Manages content notes and same-day post planning.",
            "Add note / Create Post row, scheduled posts section, notes section, note menus.",
            "Add note, create post, edit note, delete note, change note status, drag note to another day.",
            "Users who can open Content Calendar",
            "Opened from a day cell",
            "client/src/components/DayNotesModal.jsx",
        ),
        (
            "Create Post modal",
            "Calendar overlay",
            "Wide modal containing the Upload Post form",
            "Creates a post from inside the calendar with the date pre-filled.",
            "Modal shell, embedded upload form, fixed footer submit area.",
            "Create a scheduled post for the selected day.",
            "Users with Upload access",
            "Opened from Day planner modal",
            "client/src/components/CreatePostModal.jsx; client/src/components/UploadPostForm.jsx",
        ),
        (
            "Analytics",
            "/analytics",
            "Page head + stat cards + charts + ranking table",
            "Shows page performance trends and top content.",
            "Date-range controls, headline stats, trend cards, top posts table.",
            "Change range, inspect best posts.",
            "Users with Analytics access",
            "Active page",
            "client/src/pages/Analytics/AnalyticsPage.jsx",
        ),
        (
            "Post Pool",
            "/post-pool",
            "Page head + filters + card grid + viewers/modals",
            "Central management surface for all post statuses.",
            "Title area, status filters, post grid, post viewer, edit modal, delete modal, pagination.",
            "Filter posts, open a post, edit it, delete it, upload another post.",
            "Users with Post Pool access",
            "Active page",
            "client/src/pages/PostPool/PostPoolPage.jsx",
        ),
        (
            "Upload Post",
            "/upload",
            "Page head + two-column form/preview layout",
            "Creates a new post with optional media or Creatomate template output.",
            "Upload form, preview card, progress modals, render-result modal.",
            "Upload media, write a caption, schedule or post now, generate from template.",
            "Users with Upload access",
            "Active page; optional template feature flag",
            "client/src/pages/UploadPost/UploadPostPage.jsx; client/src/components/UploadPostForm.jsx",
        ),
        (
            "Settings - Posting",
            "/settings",
            "Split view with section list on the left and detail card on the right",
            "Controls general posting behavior and alerts.",
            "Section nav, posting form card.",
            "Toggle scheduled publishing, set timezone, set alert threshold, set owner email, save settings.",
            "Users with Settings access",
            "None",
            "client/src/pages/Settings/SettingsPage.jsx",
        ),
        (
            "Settings - Pages",
            "/settings",
            "Embedded section inside Settings",
            "Manages connected Facebook pages and optional Telegram bots.",
            "Section header, page cards, connect/edit form.",
            "Connect page, test credentials, save page, edit page, delete page, attach/remove Telegram bot.",
            "Admins with Settings access",
            "Pages section selected",
            "client/src/pages/Settings/FacebookPages.jsx",
        ),
        (
            "Settings - Templates",
            "/settings",
            "Embedded section inside Settings",
            "Stores reusable Creatomate template JSON definitions.",
            "Section header, template list, add/edit form.",
            "Add template, edit template, upload JSON, delete template.",
            "Users when templates feature is enabled",
            "Templates section selected and feature flag on",
            "client/src/pages/Settings/CreatomateTemplates.jsx",
        ),
        (
            "Posting Logs",
            "/logs",
            "Page head + table + pagination",
            "Shows every posting attempt the system made.",
            "Title area, logs table, empty state, pagination controls.",
            "Review errors, inspect posting history, move between pages.",
            "Users with Logs access",
            "None",
            "client/src/pages/Logs/LogsPage.jsx",
        ),
        (
            "Activity Log",
            "/activity",
            "Page head + table + pagination",
            "Shows who created, edited, tagged, or deleted content items.",
            "Title area, activity table, empty state, pagination controls.",
            "Review history and move between pages.",
            "Users with Activity access",
            "None",
            "client/src/pages/Activity/ActivityPage.jsx",
        ),
        (
            "Connections",
            "/connections",
            "Single full-height card with search-first interaction",
            "Manages teammate connection requests and current connections.",
            "Search bar, search results, incoming requests, connections list, sent requests.",
            "Send request, accept request, decline request, cancel request, remove connection.",
            "Users with Connections access",
            "None",
            "client/src/pages/Connections/ConnectionsPage.jsx",
        ),
        (
            "Vault",
            "/vault",
            "Page head + breadcrumb/actions + toolbar + item grid + modals",
            "Shared media and file browser for the workspace.",
            "Breadcrumb/action row, filter toolbar, folder/file grid, upload/new-folder/preview/delete modals.",
            "Browse folders, upload files, create folder, search, filter, sort, preview, download, delete.",
            "Users with Vault access",
            "None",
            "client/src/pages/Vault/VaultPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "/messages",
            "Left mode rail + conversation list panel + thread panel",
            "Handles customer conversations coming from connected channels.",
            "Mode rail, page filter, incoming requests bar, AI/For You tabs, conversation list, thread header, thread timeline, composer.",
            "Filter conversations, open a thread, take over AI conversations, reply as live agent, transfer conversations.",
            "Users with Messaging access",
            "Customer mode selected",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Incoming requests drawer",
            "Messaging overlay",
            "Right-side drawer over the messaging page",
            "Shows transfer requests that teammates want the user to accept.",
            "Drawer header, request list, Accept and Decline actions.",
            "Accept or decline transferred conversations.",
            "Users with Messaging access",
            "Opened from Incoming requests bar",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Transfer conversation modal",
            "Messaging overlay",
            "Modal with teammate list",
            "Lets a live agent hand the current conversation to another teammate.",
            "Modal intro, teammate list, transfer actions.",
            "Transfer the active conversation to another agent.",
            "Users with Messaging access",
            "Live-agent customer thread open",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "/messages",
            "Two-panel team chat workspace",
            "Internal direct and group chat between teammates.",
            "Conversation list/search panel, thread panel, new-group modal, group settings modal.",
            "Search teammates, start DM, create group, send attachments, manage group members.",
            "Users with Messaging access",
            "Agent mode selected",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Accounts",
            "/accounts",
            "Page head + cards + tables + admin modals",
            "Admin workspace for invite links and account lifecycle management.",
            "Header action, new-link card, accounts table, invite-links table, account details modal, module-access modal.",
            "Generate login links, copy links, activate/deactivate accounts, delete accounts, inspect account details.",
            "Admins only",
            "None",
            "client/src/pages/Accounts/AccountsPage.jsx",
        ),
        (
            "User Profile",
            "/profile",
            "Page head + stacked cards + avatar crop dialog",
            "Lets the user update personal account details.",
            "Profile hero card, account details form, status card, avatar crop dialog.",
            "Change avatar, update name/email, open change-password flow.",
            "Authenticated users",
            "None",
            "client/src/pages/Profile/ProfilePage.jsx",
        ),
        (
            "Change Password",
            "/profile/change-password",
            "Focused multi-step security flow",
            "Guides the user through password verification, email code check, and new password entry.",
            "Back link, step indicator, stage card, verification-code modal.",
            "Continue, enter code, verify, resend code, update password.",
            "Authenticated users",
            "Reached from User Profile",
            "client/src/pages/Profile/ChangePasswordPage.jsx",
        ),
        (
            "User menu overlay",
            "Sidebar footer overlay",
            "Compact dropdown menu",
            "Fast account-level actions from anywhere inside the app shell.",
            "Profile summary, menu links, theme toggle, logout.",
            "Open profile, open privacy policy, switch theme, logout.",
            "Authenticated users",
            "Opened from account menu button",
            "client/src/components/AppLayout.jsx",
        ),
    ],
)


CONTROL_COLUMNS = [
    "Screen",
    "Section",
    "Control",
    "Type",
    "Viewport Position",
    "Meaning",
    "Purpose",
    "When Visible",
    "Assistant Guidance",
    "Source",
]
CONTROL_ROWS = make_rows(
    CONTROL_COLUMNS,
    [
        (
            "App shell",
            "Sidebar top",
            "Sidebar collapse",
            "Button",
            "Top of left desktop sidebar",
            "Shrinks or expands the sidebar.",
            "Gives more content space on desktop.",
            "Desktop layout",
            "Tell the user to click the chevron at the top of the left sidebar.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "App shell",
            "Sidebar navigation",
            "Workspace links",
            "Nav links",
            "Upper half of left sidebar",
            "Primary page-scoped routes.",
            "Moves between Dashboard, Calendar, Analytics, Post Pool, and Upload.",
            "Authenticated layout",
            "Guide the user to the left sidebar under the 'Workspace' heading.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "App shell",
            "Sidebar navigation",
            "General links",
            "Nav links",
            "Lower half of left sidebar",
            "Shared tools and admin routes.",
            "Moves between Messaging, Connections, Vault, Logs, Activity, Accounts, and Settings.",
            "Authenticated layout",
            "Guide the user to the left sidebar under the 'General' heading.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "App shell",
            "Page card",
            "Switch Page",
            "Button",
            "Sidebar footer, first card",
            "Opens the active-page selector.",
            "Changes the page context for page-scoped screens.",
            "When at least one page is connected",
            "Tell the user to look at the bottom-left page card and press 'Switch Page'.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "App shell",
            "User card",
            "Account menu button",
            "Button",
            "Sidebar footer, bottom card",
            "Opens profile and account actions.",
            "Accesses profile, privacy, theme, and logout.",
            "Authenticated layout",
            "Tell the user to click their name/avatar at the bottom-left corner.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "App shell",
            "Mobile topbar",
            "Open menu",
            "Button",
            "Top-left of viewport on mobile",
            "Shows the hidden sidebar drawer.",
            "Makes navigation available on narrow screens.",
            "Mobile layout",
            "Tell mobile users to tap the hamburger icon in the top-left corner.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Switch Page modal",
            "Header",
            "Refresh page data",
            "Icon button",
            "Top-right of modal header",
            "Refreshes page names and follower counts from Facebook.",
            "Updates page metadata and marks expired tokens.",
            "When Switch Page modal is open",
            "Ask the user to click the refresh icon in the top-right of the modal.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Switch Page modal",
            "Page list",
            "Page row",
            "Selectable row",
            "Center of modal body",
            "Represents one connected page.",
            "Switches the app to that page.",
            "When Switch Page modal is open",
            "Tell the user to click the page name row they want to activate.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Switch Page modal",
            "Page list",
            "Update expired page",
            "Button",
            "Right side of an expired page row",
            "Shortcut to fix an expired page token.",
            "Takes an admin to Settings -> Facebook Pages.",
            "Only for expired pages and admins",
            "Guide the user to click 'Update' beside the expired page.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Switch Page modal",
            "Footer",
            "Add page",
            "Button",
            "Bottom of modal",
            "Opens page connection settings.",
            "Lets admins add another page.",
            "Admins only",
            "Tell the user to use the footer button if they need to connect a new page.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "User menu overlay",
            "Menu body",
            "User Profile",
            "Menu item",
            "Upper section of account dropdown",
            "Opens the profile page.",
            "Lets the user update personal account details.",
            "When the user menu is open",
            "Tell the user to click 'User Profile' in the account dropdown.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "User menu overlay",
            "Menu body",
            "Privacy Policy",
            "Menu item",
            "Middle section of account dropdown",
            "Opens the legal/privacy page.",
            "Lets the user review data and policy details.",
            "When the user menu is open",
            "Tell the user to click 'Privacy Policy' in the account dropdown.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "User menu overlay",
            "Menu body",
            "Theme toggle",
            "Menu item",
            "Middle section of account dropdown",
            "Switches between light and dark theme.",
            "Changes the app appearance.",
            "When the user menu is open",
            "Tell the user to click 'Light theme' or 'Dark theme' in the account dropdown.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "User menu overlay",
            "Menu footer",
            "Logout",
            "Menu item",
            "Bottom section of account dropdown",
            "Signs the user out.",
            "Ends the session.",
            "When the user menu is open",
            "Tell the user to click 'Logout' at the bottom of the account dropdown.",
            "client/src/components/AppLayout.jsx",
        ),
        (
            "Login",
            "Form",
            "Email",
            "Input",
            "Center card, first field",
            "Account email address.",
            "Identifies the user.",
            "Login page",
            "Ask the user to enter their email in the first field of the login card.",
            "client/src/pages/Login/LoginPage.jsx",
        ),
        (
            "Login",
            "Form",
            "Password",
            "Password input",
            "Center card, second field",
            "Account password.",
            "Authenticates the user.",
            "Login page",
            "Ask the user to enter their password in the second field of the login card.",
            "client/src/pages/Login/LoginPage.jsx",
        ),
        (
            "Login",
            "Form",
            "Log in",
            "Primary button",
            "Bottom of login form",
            "Submits login credentials.",
            "Signs the user into the app.",
            "Login page",
            "Tell the user to press the full-width 'Log in' button below the fields.",
            "client/src/pages/Login/LoginPage.jsx",
        ),
        (
            "Login",
            "Footer",
            "Privacy Policy",
            "Link",
            "Bottom of auth card",
            "Opens the privacy policy page.",
            "Provides a public legal reference.",
            "Login page",
            "Tell the user to use the small footer link under the invite-only note.",
            "client/src/pages/Login/LoginPage.jsx",
        ),
        (
            "Signup",
            "Form",
            "Name",
            "Input",
            "Center card, first field",
            "Display name for the new account.",
            "Creates the user profile.",
            "Valid invite state",
            "Tell the user to start with the Name field at the top of the signup form.",
            "client/src/pages/Signup/SignupPage.jsx",
        ),
        (
            "Signup",
            "Form",
            "Email",
            "Input",
            "Center card, second field",
            "Email for the new account.",
            "Creates the login identity.",
            "Valid invite state",
            "Tell the user to enter the account email in the second field.",
            "client/src/pages/Signup/SignupPage.jsx",
        ),
        (
            "Signup",
            "Form",
            "Password",
            "Password input",
            "Center card, third field",
            "New account password.",
            "Creates the secret credential.",
            "Valid invite state",
            "Tell the user to enter a password with at least 8 characters.",
            "client/src/pages/Signup/SignupPage.jsx",
        ),
        (
            "Signup",
            "Form",
            "Confirm password",
            "Password input",
            "Center card, fourth field",
            "Re-entry of the new password.",
            "Prevents password typos.",
            "Valid invite state",
            "Tell the user to retype the same password in the confirm field.",
            "client/src/pages/Signup/SignupPage.jsx",
        ),
        (
            "Signup",
            "Form",
            "Create account",
            "Primary button",
            "Bottom of signup form",
            "Submits the new account.",
            "Finishes signup.",
            "Valid invite state",
            "Tell the user to press the full-width 'Create account' button after filling the form.",
            "client/src/pages/Signup/SignupPage.jsx",
        ),
        (
            "Dashboard",
            "Page head",
            "+ Upload post",
            "Primary button",
            "Top-right of page head",
            "Shortcut into post creation.",
            "Opens the Upload screen.",
            "Dashboard page",
            "Tell the user to use the top-right '+ Upload post' button.",
            "client/src/pages/Dashboard/DashboardPage.jsx",
        ),
        (
            "Dashboard",
            "Automation card",
            "Edit settings",
            "Button",
            "Right side of Automation card footer",
            "Opens posting settings.",
            "Lets the user change automation behavior.",
            "Dashboard page",
            "Send the user to the Automation card and its 'Edit settings' button.",
            "client/src/pages/Dashboard/DashboardPage.jsx",
        ),
        (
            "Dashboard",
            "Pipeline card",
            "Manage pool",
            "Button",
            "Left action in Pipeline card",
            "Opens the Post Pool.",
            "Lets the user review scheduled and stored posts.",
            "Dashboard page",
            "Guide the user to the Pipeline card and then the 'Manage pool' button.",
            "client/src/pages/Dashboard/DashboardPage.jsx",
        ),
        (
            "Dashboard",
            "Pipeline card",
            "View logs",
            "Button",
            "Right action in Pipeline card",
            "Opens Posting Logs.",
            "Lets the user inspect publish attempts and failures.",
            "Dashboard page",
            "Guide the user to the Pipeline card and then 'View logs'.",
            "client/src/pages/Dashboard/DashboardPage.jsx",
        ),
        (
            "Content Calendar",
            "Calendar header",
            "Today",
            "Button",
            "Top-right of calendar card header",
            "Returns the calendar to the current month.",
            "Quick month reset.",
            "Calendar page",
            "Tell the user to click 'Today' in the calendar header.",
            "client/src/components/CalendarMonth.jsx",
        ),
        (
            "Content Calendar",
            "Calendar header",
            "Previous month / Next month",
            "Icon buttons",
            "Top-right of calendar card header",
            "Moves the visible month backward or forward.",
            "Navigates the calendar timeline.",
            "Calendar page",
            "Tell the user to use the left or right chevron beside 'Today'.",
            "client/src/components/CalendarMonth.jsx",
        ),
        (
            "Content Calendar",
            "Month grid",
            "Day cell",
            "Clickable cell",
            "Main calendar grid",
            "Represents one calendar day.",
            "Opens the day planner modal.",
            "Calendar page",
            "Tell the user to click the date cell they want to inspect.",
            "client/src/components/CalendarMonth.jsx",
        ),
        (
            "Day planner modal",
            "Top actions",
            "Add note",
            "Button",
            "Top of modal body, left action",
            "Starts composing a planning note for the selected day.",
            "Captures planning context without scheduling a post.",
            "When the day planner modal is open",
            "Tell the user to click 'Add note' near the top of the day modal.",
            "client/src/components/DayNotesModal.jsx",
        ),
        (
            "Day planner modal",
            "Top actions",
            "Create Post",
            "Button",
            "Top of modal body, next to Add note",
            "Opens the Create Post modal for that date.",
            "Schedules a post directly from the calendar.",
            "Future dates only",
            "Tell the user to click 'Create Post' in the day planner.",
            "client/src/components/DayNotesModal.jsx",
        ),
        (
            "Day planner modal",
            "Compose area",
            "Add note submit",
            "Primary button",
            "Bottom-right of note compose block",
            "Saves the typed note for that day.",
            "Creates a planning note.",
            "While composing a new note",
            "Tell the user to press 'Add note' inside the compose block after writing the note.",
            "client/src/components/DayNotesModal.jsx",
        ),
        (
            "Day planner modal",
            "Notes list",
            "Status chip",
            "Button",
            "Right side of each note row",
            "Shows the note status and opens a status picker.",
            "Updates note state such as Pending or Completed.",
            "For each note row",
            "Tell the user to click the status chip on the note row they want to update.",
            "client/src/components/DayNotesModal.jsx",
        ),
        (
            "Day planner modal",
            "Notes list",
            "Note options",
            "Icon button",
            "Far right of each note row",
            "Opens note actions and metadata.",
            "Lets the user edit or delete a note.",
            "For each note row",
            "Tell the user to click the three-dot options button on the note row.",
            "client/src/components/DayNotesModal.jsx",
        ),
        (
            "Day planner modal",
            "Notes list",
            "Drag handle",
            "Drag target",
            "Left side of each note row",
            "Lets the user move a note to another day.",
            "Supports drag-and-drop rescheduling of notes.",
            "For each note row",
            "Tell the user to drag the grip handle onto another calendar date.",
            "client/src/components/DayNotesModal.jsx",
        ),
        (
            "Analytics",
            "Page head",
            "7 days / 28 days / 90 days",
            "Segmented buttons",
            "Top-right of page head",
            "Selects the reporting time range.",
            "Updates stats and charts.",
            "Analytics page",
            "Tell the user to use the range buttons in the top-right of the Analytics header.",
            "client/src/pages/Analytics/AnalyticsPage.jsx",
        ),
        (
            "Analytics",
            "Top posts table",
            "Post row link",
            "Link",
            "Lower table area",
            "Represents a high-performing post.",
            "Takes the user to the Post Pool.",
            "When rankings are available",
            "Guide the user to click the post title in the Top posts table.",
            "client/src/pages/Analytics/AnalyticsPage.jsx",
        ),
        (
            "Post Pool",
            "Page head",
            "+ Upload post",
            "Primary button",
            "Top-right of page head",
            "Creates another post.",
            "Opens the Upload screen.",
            "Post Pool page",
            "Tell the user to use the top-right '+ Upload post' button.",
            "client/src/pages/PostPool/PostPoolPage.jsx",
        ),
        (
            "Post Pool",
            "Filter bar",
            "Status filters",
            "Filter chips",
            "Below the page head, across the page",
            "Limit the visible posts by status.",
            "Focuses the list on ready, posted, failed, archived, and similar states.",
            "Post Pool page",
            "Tell the user to click the relevant status chip above the post grid.",
            "client/src/pages/PostPool/PostPoolPage.jsx",
        ),
        (
            "Post Pool",
            "Post grid",
            "Post card",
            "Clickable card",
            "Main grid area",
            "Represents one post record.",
            "Opens the fullscreen Post Viewer.",
            "When posts exist",
            "Tell the user to click the post card they want to inspect.",
            "client/src/pages/PostPool/PostPoolPage.jsx",
        ),
        (
            "Post Pool",
            "Post grid",
            "Card options",
            "Menu trigger",
            "Top-right of a post card",
            "Opens Edit and Delete actions.",
            "Lets the user manage a specific post.",
            "When posts exist",
            "Tell the user to use the menu button on the target post card.",
            "client/src/pages/PostPool/PostPoolPage.jsx",
        ),
        (
            "Post Pool",
            "Edit modal",
            "Save changes",
            "Primary button",
            "Bottom-right of edit dialog",
            "Persists edits to caption or schedule.",
            "Updates the selected post.",
            "When edit modal is open",
            "Tell the user to finish edits and click 'Save changes'.",
            "client/src/pages/PostPool/PostPoolPage.jsx",
        ),
        (
            "Post Pool",
            "Delete modal",
            "Delete",
            "Danger button",
            "Bottom-right of delete dialog",
            "Confirms a post deletion.",
            "Removes the selected post.",
            "When delete modal is open",
            "Tell the user to click 'Delete' only after confirming the post is the correct one.",
            "client/src/pages/PostPool/PostPoolPage.jsx",
        ),
        (
            "Post Pool",
            "Pagination",
            "Prev / Next",
            "Buttons",
            "Bottom of page",
            "Moves between pages of post results.",
            "Browses older or newer post cards.",
            "When more than one page of results exists",
            "Tell the user to use the bottom pagination buttons.",
            "client/src/pages/PostPool/PostPoolPage.jsx",
        ),
        (
            "Upload Post",
            "Form top",
            "Use template",
            "Toggle",
            "Near top of upload form",
            "Switches the form into Creatomate template mode.",
            "Uses a saved video template instead of direct media upload.",
            "When templates feature is enabled",
            "Tell the user to enable 'Use template' near the top of the form if they want a rendered template video.",
            "client/src/components/UploadPostForm.jsx",
        ),
        (
            "Upload Post",
            "Media area",
            "Media dropzone",
            "Dropzone",
            "Upper-middle of upload form",
            "Accepts image or video files.",
            "Adds media to the post.",
            "When template mode is off",
            "Tell the user to drag a file into the Media area or click it to choose a file.",
            "client/src/components/UploadPostForm.jsx",
        ),
        (
            "Upload Post",
            "Template area",
            "Template dropdown",
            "Dropdown",
            "Upper-middle of upload form",
            "Selects a saved Creatomate template.",
            "Defines which template will render the final video.",
            "When template mode is on",
            "Tell the user to pick the template from the Template dropdown before generating.",
            "client/src/components/UploadPostForm.jsx",
        ),
        (
            "Upload Post",
            "Template area",
            "Input video",
            "Dropzone",
            "Below the template dropdown",
            "Accepts the raw video clip used by the template.",
            "Supplies the source media for rendering.",
            "When template mode is on",
            "Tell the user to add a video to the Input video area before generating.",
            "client/src/components/UploadPostForm.jsx",
        ),
        (
            "Upload Post",
            "Template area",
            "Generate with Template",
            "Primary button",
            "Right side below template inputs",
            "Starts the Creatomate render flow.",
            "Produces a generated video preview for the post.",
            "When template mode is on and an input video exists",
            "Tell the user to click 'Generate with Template' after choosing a template and input video.",
            "client/src/components/UploadPostForm.jsx",
        ),
        (
            "Upload Post",
            "Form middle",
            "Caption",
            "Textarea",
            "Middle of upload form",
            "Text that accompanies the post.",
            "Provides the copy for the post.",
            "Upload form",
            "Tell the user to use the Caption box in the middle of the form.",
            "client/src/components/UploadPostForm.jsx",
        ),
        (
            "Upload Post",
            "Scheduling",
            "Scheduled posting",
            "Toggle",
            "Lower-middle of upload form",
            "Chooses between future scheduling and immediate posting.",
            "Changes whether the form asks for a date/time or posts on the next run.",
            "Upload form",
            "Tell the user to switch off Scheduled posting if they want the content sent right away.",
            "client/src/components/UploadPostForm.jsx",
        ),
        (
            "Upload Post",
            "Scheduling",
            "Schedule date and time",
            "Date input and time select",
            "Lower-middle of upload form",
            "Defines the exact slot for a scheduled post.",
            "Schedules the content into a single time slot.",
            "When Scheduled posting is on",
            "Tell the user to choose both the date and time in the Schedule section.",
            "client/src/components/UploadPostForm.jsx",
        ),
        (
            "Upload Post",
            "Submit",
            "Add to pool / Post now",
            "Primary button",
            "Bottom of form",
            "Submits the post.",
            "Creates the scheduled post or sends it immediately.",
            "Upload form",
            "Tell the user to press the large submit button at the bottom of the form.",
            "client/src/components/UploadPostForm.jsx",
        ),
        (
            "Settings - Posting",
            "Section list",
            "Posting / Pages / Templates",
            "Section navigation",
            "Left column of Settings page",
            "Changes which settings section is visible.",
            "Moves between general posting, page integration, and template settings.",
            "Settings page",
            "Tell the user to use the left-side section list inside Settings.",
            "client/src/pages/Settings/SettingsPage.jsx",
        ),
        (
            "Settings - Posting",
            "Posting form",
            "Scheduled publishing",
            "Toggle",
            "Right panel, near top of Posting section",
            "Turns automated scheduled publishing on or off.",
            "Controls the main automation switch.",
            "Posting section selected",
            "Tell the user to use the Scheduled publishing toggle near the top of the settings form.",
            "client/src/pages/Settings/SettingsPage.jsx",
        ),
        (
            "Settings - Posting",
            "Posting form",
            "Timezone",
            "Select",
            "Right panel, upper-middle of Posting section",
            "Defines which timezone scheduling uses.",
            "Aligns post times with the intended timezone.",
            "Posting section selected",
            "Tell the user to choose the timezone in the Timezone field.",
            "client/src/pages/Settings/SettingsPage.jsx",
        ),
        (
            "Settings - Posting",
            "Posting form",
            "Low-pool alert threshold",
            "Number input",
            "Right panel, middle of Posting section",
            "Minimum ready-post count that triggers an alert.",
            "Warns the owner when content is running low.",
            "Posting section selected",
            "Tell the user to set the threshold in the Low-pool alert field.",
            "client/src/pages/Settings/SettingsPage.jsx",
        ),
        (
            "Settings - Posting",
            "Posting form",
            "Owner email",
            "Email input",
            "Right panel, lower-middle of Posting section",
            "Destination for alert and operational emails.",
            "Defines who receives low-pool alerts.",
            "Posting section selected",
            "Tell the user to enter the alert recipient in Owner email.",
            "client/src/pages/Settings/SettingsPage.jsx",
        ),
        (
            "Settings - Posting",
            "Posting form",
            "Save settings",
            "Primary button",
            "Bottom of right-side settings card",
            "Persists posting configuration.",
            "Saves the current posting settings.",
            "Posting section selected",
            "Tell the user to click 'Save settings' after adjusting the form.",
            "client/src/pages/Settings/SettingsPage.jsx",
        ),
        (
            "Settings - Pages",
            "Section header",
            "+ Connect page",
            "Button",
            "Top-right of Facebook Pages section",
            "Starts the connect-page workflow.",
            "Adds a new Facebook page integration.",
            "When not already editing a page",
            "Tell the user to use '+ Connect page' at the top of the Facebook Pages section.",
            "client/src/pages/Settings/FacebookPages.jsx",
        ),
        (
            "Settings - Pages",
            "Connect/edit form",
            "Connect / Add page / Save",
            "Primary button",
            "Bottom-right of Facebook Pages form",
            "Two-step primary action that first tests credentials, then saves the page.",
            "Validates Facebook access and persists the page connection.",
            "While adding or editing a page",
            "Explain that the first click tests the connection and the next click saves after verification succeeds.",
            "client/src/pages/Settings/FacebookPages.jsx",
        ),
        (
            "Settings - Pages",
            "Connect/edit form",
            "Remove bot",
            "Checkbox",
            "Telegram bot area in page edit form",
            "Marks an attached Telegram bot for removal.",
            "Detaches the Telegram bot when the page is saved.",
            "When editing a page that already has a Telegram bot",
            "Tell the user to tick 'Remove bot' before saving if they want the Telegram bot detached.",
            "client/src/pages/Settings/FacebookPages.jsx",
        ),
        (
            "Settings - Pages",
            "Page cards",
            "Page options",
            "Menu trigger",
            "Right side of each connected page card",
            "Opens Edit and Delete for the selected page.",
            "Manages an existing connection.",
            "When connected pages exist",
            "Tell the user to use the options button on the page card they want to edit or remove.",
            "client/src/pages/Settings/FacebookPages.jsx",
        ),
        (
            "Settings - Templates",
            "Section header",
            "+ Add template",
            "Button",
            "Top-right of Creatomate Templates section",
            "Starts a new template definition.",
            "Adds a reusable video template.",
            "When not already editing a template",
            "Tell the user to use '+ Add template' at the top of the template section.",
            "client/src/pages/Settings/CreatomateTemplates.jsx",
        ),
        (
            "Settings - Templates",
            "Edit form",
            "Template JSON",
            "Textarea",
            "Main body of template form",
            "Stores the Creatomate configuration JSON.",
            "Defines the render template that Upload Post can reuse.",
            "While adding or editing a template",
            "Tell the user to paste the JSON into the large Template JSON box.",
            "client/src/pages/Settings/CreatomateTemplates.jsx",
        ),
        (
            "Settings - Templates",
            "Edit form",
            "Upload .json",
            "Button",
            "Bottom actions of template form",
            "Loads a JSON file into the editor.",
            "Speeds up template entry from a saved file.",
            "While adding or editing a template",
            "Tell the user to use 'Upload .json' if they already have the template config file.",
            "client/src/pages/Settings/CreatomateTemplates.jsx",
        ),
        (
            "Settings - Templates",
            "Edit form",
            "Save / Add",
            "Primary button",
            "Bottom-right of template form",
            "Persists the template definition.",
            "Creates or updates the template.",
            "While adding or editing a template",
            "Tell the user to click the final Save or Add button after validating the JSON.",
            "client/src/pages/Settings/CreatomateTemplates.jsx",
        ),
        (
            "Posting Logs",
            "Pagination",
            "Prev / Next",
            "Buttons",
            "Bottom of logs table",
            "Moves through log pages.",
            "Browses more posting history.",
            "When more than one logs page exists",
            "Tell the user to use the pagination buttons at the bottom of the logs table.",
            "client/src/pages/Logs/LogsPage.jsx",
        ),
        (
            "Activity Log",
            "Pagination",
            "Prev / Next",
            "Buttons",
            "Bottom of activity table",
            "Moves through activity pages.",
            "Browses more audit history.",
            "When more than one activity page exists",
            "Tell the user to use the pagination buttons at the bottom of the activity table.",
            "client/src/pages/Activity/ActivityPage.jsx",
        ),
        (
            "Connections",
            "Search header",
            "Search teammates to connect",
            "Input",
            "Top of the main card",
            "Searches workspace teammates by name or email.",
            "Finds people to connect with.",
            "Connections page",
            "Tell the user to use the search field at the top of the Connections card.",
            "client/src/pages/Connections/ConnectionsPage.jsx",
        ),
        (
            "Connections",
            "Search results",
            "Connect / Accept / Cancel request / Remove",
            "Action buttons",
            "Right side of each search result row",
            "Changes the relationship with the selected teammate.",
            "Starts, accepts, cancels, or removes a connection.",
            "When a search query is active",
            "Tell the user to choose the action button shown beside the teammate they searched for.",
            "client/src/pages/Connections/ConnectionsPage.jsx",
        ),
        (
            "Connections",
            "Connection requests",
            "Accept / Decline",
            "Action buttons",
            "Right side of each incoming request row",
            "Handles incoming connection requests.",
            "Accepts or rejects the request.",
            "When incoming requests exist and no search query is active",
            "Tell the user to go to the 'Connection requests' section and use Accept or Decline.",
            "client/src/pages/Connections/ConnectionsPage.jsx",
        ),
        (
            "Connections",
            "Your connections",
            "Remove",
            "Action button",
            "Right side of each connection row",
            "Breaks an existing teammate connection.",
            "Stops direct communication access between those agents.",
            "When connections exist and no search query is active",
            "Tell the user to use the Remove action in the 'Your connections' section.",
            "client/src/pages/Connections/ConnectionsPage.jsx",
        ),
        (
            "Connections",
            "Sent requests",
            "Cancel",
            "Action button",
            "Right side of each sent request row",
            "Withdraws an outgoing request.",
            "Cancels a pending connection request.",
            "When sent requests exist and no search query is active",
            "Tell the user to use the Cancel action in the 'Sent requests' section.",
            "client/src/pages/Connections/ConnectionsPage.jsx",
        ),
        (
            "Vault",
            "Page head",
            "Create a new folder",
            "Button",
            "Top-right of the Vault card header",
            "Opens folder creation flow.",
            "Creates a folder in the current location.",
            "Vault page",
            "Tell the user to use 'Create a new folder' at the top-right of the Vault screen.",
            "client/src/pages/Vault/VaultPage.jsx",
        ),
        (
            "Vault",
            "Page head",
            "Upload files",
            "Button",
            "Top-right of the Vault card header",
            "Starts file upload.",
            "Adds files into the current folder.",
            "Vault page",
            "Tell the user to use the 'Upload files' button beside the folder action.",
            "client/src/pages/Vault/VaultPage.jsx",
        ),
        (
            "Vault",
            "Toolbar",
            "Breadcrumb path",
            "Breadcrumb",
            "Top-left of the main Vault card",
            "Shows the current folder path starting from Main.",
            "Helps the user understand where they are.",
            "Vault page",
            "Reference the breadcrumb when explaining where a file or folder lives.",
            "client/src/pages/Vault/VaultPage.jsx",
        ),
        (
            "Vault",
            "Toolbar",
            "Back",
            "Button",
            "Left side of toolbar when inside a folder",
            "Moves up one folder level.",
            "Returns to the parent folder.",
            "When not at the top-level folder",
            "Tell the user to use the Back button in the Vault toolbar.",
            "client/src/pages/Vault/VaultPage.jsx",
        ),
        (
            "Vault",
            "Toolbar",
            "Search",
            "Input",
            "Center-left of toolbar",
            "Searches within the current folder view.",
            "Finds folders or files by name.",
            "Vault page",
            "Tell the user to type into the search box in the toolbar.",
            "client/src/pages/Vault/VaultPage.jsx",
        ),
        (
            "Vault",
            "Toolbar",
            "Type filter",
            "Dropdown",
            "Center of toolbar",
            "Filters items by folders, images, videos, documents, or other files.",
            "Narrows the item grid.",
            "Vault page",
            "Tell the user to choose the item type from the Type dropdown in the toolbar.",
            "client/src/pages/Vault/VaultPage.jsx",
        ),
        (
            "Vault",
            "Toolbar",
            "Sort",
            "Dropdown",
            "Center-right of toolbar",
            "Changes item ordering.",
            "Sorts by name, newest, or size.",
            "Vault page",
            "Tell the user to use the Sort dropdown beside the Type filter.",
            "client/src/pages/Vault/VaultPage.jsx",
        ),
        (
            "Vault",
            "Toolbar",
            "Clear filters",
            "Button",
            "Right side of toolbar",
            "Resets current search/filter state.",
            "Returns the grid to the unfiltered view.",
            "Only when filters are active",
            "Tell the user to use 'Clear filters' if the expected item is hidden by search or filter state.",
            "client/src/pages/Vault/VaultPage.jsx",
        ),
        (
            "Vault",
            "Item grid",
            "Folder card",
            "Clickable card",
            "Main content grid",
            "Represents a folder.",
            "Opens that folder.",
            "When folders exist",
            "Tell the user to click the folder card to enter it.",
            "client/src/pages/Vault/VaultPage.jsx",
        ),
        (
            "Vault",
            "Item grid",
            "File actions",
            "Card actions",
            "On each file card",
            "Preview, download, or delete a file.",
            "Acts on a specific file.",
            "When files exist",
            "Tell the user to open the file card and use its action buttons for preview, download, or delete.",
            "client/src/pages/Vault/VaultPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Mode rail",
            "Agent to Agent / Agent to Customer",
            "Mode buttons",
            "Far left side of messaging page",
            "Switches between internal chat and customer chat surfaces.",
            "Changes the entire messaging workspace mode.",
            "Messaging page",
            "Tell the user to use the left-side mode rail first if they are in the wrong chat mode.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Conversation list header",
            "Page filter",
            "Dropdown trigger",
            "Top-right of conversation list panel",
            "Filters customer conversations by page or all pages.",
            "Narrows the inbox to a selected page.",
            "Customer mode",
            "Tell the user to open the filter at the top-right of the conversation list panel.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Conversation list",
            "Incoming requests",
            "Drawer trigger",
            "Under the conversation list header",
            "Opens transfer requests sent by teammates.",
            "Lets the user accept or decline transferred conversations.",
            "Customer mode",
            "Tell the user to click the 'Incoming requests' bar below the list header.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Conversation list",
            "AI Agent / For You",
            "Segmented tabs",
            "Under Incoming requests bar",
            "Switches between AI-handled and live-agent queues.",
            "Changes which conversations are listed.",
            "Customer mode",
            "Tell the user to choose 'AI Agent' for AI-managed threads or 'For You' for their live-agent queue.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Conversation list",
            "Conversation row",
            "Selectable row",
            "Left panel list body",
            "Represents one customer conversation.",
            "Opens that thread in the right panel.",
            "When conversations exist",
            "Tell the user to click the customer row on the left to open the chat.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Thread header",
            "Transfer conversation",
            "Icon button",
            "Top-right of open thread header",
            "Transfers a live-agent conversation to another teammate.",
            "Opens the transfer modal.",
            "Only on live-agent threads assigned to the current user",
            "Tell the user to use the transfer icon in the upper-right of the thread header.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Thread body",
            "Copy message",
            "Icon button",
            "Lower area of each text bubble",
            "Copies a message body to the clipboard.",
            "Makes it easy to reuse or quote message text.",
            "When a message has text",
            "Tell the user to hover or inspect the message bubble and use the copy icon in its footer.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Thread body",
            "Reply to message",
            "Icon button",
            "Right side of each bubble stack",
            "Starts a reply-to context for a specific message.",
            "Anchors the next outgoing message to an earlier bubble.",
            "Live-agent threads",
            "Tell the user to use the reply icon beside the message they want to answer directly.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Thread body",
            "Scroll to latest",
            "Floating button",
            "Bottom-right inside the thread area",
            "Jumps back to the newest messages.",
            "Helps when the reader has scrolled up.",
            "When the user is far above the bottom of the thread",
            "Tell the user to click the floating down-arrow button near the bottom-right of the thread.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Composer",
            "Attach from Main",
            "Icon button",
            "Left side of composer bar",
            "Opens the Vault picker for attachments.",
            "Lets the user attach existing Vault media to a message.",
            "Live-agent threads",
            "Tell the user to use the image-style icon on the left side of the composer.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Composer",
            "Templates",
            "Icon button",
            "Left side of composer bar, next to Attach",
            "Opens saved text templates.",
            "Lets the user insert a reusable reply into the draft.",
            "Live-agent threads",
            "Tell the user to click the template icon beside the attachment icon.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Composer",
            "Message input",
            "Input",
            "Center of composer bar",
            "Draft field for the outgoing reply.",
            "Holds the reply text.",
            "Live-agent threads",
            "Tell the user to type in the main input at the bottom of the thread.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Composer",
            "AI enhance",
            "Inline icon button",
            "Inside the right side of the message input wrapper",
            "Placeholder affordance for AI-assisted wording.",
            "Reserved for future draft enhancement behavior.",
            "Live-agent threads",
            "If asked today, explain it is present in the composer but future behavior may be discussed later.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Composer",
            "Send message",
            "Icon button",
            "Far right of composer bar",
            "Sends the current draft and attachments.",
            "Delivers the live-agent reply.",
            "Live-agent threads with content in the composer",
            "Tell the user to press the send icon on the far right of the composer.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Customer",
            "Locked composer",
            "Take over conversation",
            "Primary button",
            "Bottom of thread panel when viewing an AI thread",
            "Moves the conversation from AI handling to a live agent.",
            "Lets the user reply directly to the customer.",
            "AI Agent threads only",
            "Explain that taking over cannot be reverted and is done from the button at the bottom of the thread.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Incoming requests drawer",
            "Request rows",
            "Accept / Decline",
            "Action buttons",
            "Right side of each request row",
            "Resolves a teammate transfer request.",
            "Accept moves the conversation to the user; Decline rejects it.",
            "When incoming requests exist",
            "Tell the user to open Incoming requests and choose Accept or Decline on the target row.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Transfer conversation modal",
            "Teammate list",
            "Teammate row",
            "Selectable row",
            "Modal body",
            "Represents one agent who can receive the conversation.",
            "Transfers the current conversation to that teammate.",
            "When the transfer modal is open",
            "Tell the user to click the teammate row in the modal to hand off the conversation.",
            "client/src/pages/Messaging/MessagingPage.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "List header",
            "New group",
            "Button",
            "Top-right of left team-chat panel",
            "Starts a new group chat.",
            "Opens the New group chat modal.",
            "Agent mode",
            "Tell the user to use the 'New group' button at the top-right of the left panel.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "Search",
            "Search teammates or chats",
            "Input",
            "Top of left team-chat panel",
            "Searches existing conversations and teammates.",
            "Finds a chat or starts a new direct message.",
            "Agent mode",
            "Tell the user to use the search field near the top of the left panel.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "Conversation list",
            "Conversation row",
            "Selectable row",
            "Left panel list body",
            "Represents a direct or group chat.",
            "Opens the selected internal conversation.",
            "When team conversations exist",
            "Tell the user to click the teammate or group row on the left.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "Suggestions / results",
            "Start a new chat",
            "Selectable row",
            "Lower left panel when search results or suggestions appear",
            "Creates a direct message with a teammate not already in the list.",
            "Starts a new DM conversation.",
            "When search or suggestions return teammates",
            "Tell the user to click a teammate under 'Start a new chat' or 'Suggested'.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "Composer",
            "Attach from Main",
            "Icon button",
            "Left side of composer bar",
            "Opens the Vault picker for attachments.",
            "Attaches Vault media to an internal message.",
            "When the current conversation allows replies",
            "Tell the user to click the attachment icon on the left side of the composer.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "Composer",
            "Message your teammate",
            "Input",
            "Center of composer bar",
            "Draft field for internal chat.",
            "Holds the outgoing message text.",
            "When the current conversation allows replies",
            "Tell the user to type in the composer input at the bottom of the thread.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "Composer",
            "Send message",
            "Icon button",
            "Far right of composer bar",
            "Sends the draft and attachments to the teammate or group.",
            "Delivers the internal message.",
            "When the current conversation allows replies and content exists",
            "Tell the user to press the send icon on the right side of the composer.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "Locked composer",
            "Accept connection request / Send connection request",
            "Primary button",
            "Bottom of thread panel when canReply is false",
            "Unlocks the ability to reply in a direct message.",
            "Creates or accepts the teammate connection required for messaging.",
            "When a DM exists without a valid connection",
            "Explain that the button appears at the bottom of the thread and must be used before replying.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "Thread header",
            "Manage",
            "Button",
            "Top-right of a group chat thread header",
            "Opens group settings.",
            "Lets the user rename the group or manage members.",
            "Group chats only",
            "Tell the user to open the group and click 'Manage' in the thread header.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "New group modal",
            "Create group",
            "Primary button",
            "Bottom-right of New group modal",
            "Creates a group chat from the selected teammates.",
            "Starts the group conversation.",
            "When group name and at least one teammate are selected",
            "Tell the user to complete the group name and picks, then click 'Create group'.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "Group settings modal",
            "Rename",
            "Primary button",
            "Right side of group-name row",
            "Renames the current group.",
            "Updates the chat title.",
            "Group settings modal",
            "Tell the user to edit the group name field and click 'Rename'.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "Group settings modal",
            "Search teammates to add",
            "Input",
            "Lower middle of group settings modal",
            "Finds teammates who are not yet in the group.",
            "Supports adding new group members.",
            "Group settings modal",
            "Tell the user to search in the Add members field, then click a result row.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "Group settings modal",
            "Remove",
            "Inline button",
            "Right side of a member row",
            "Removes that member from the group.",
            "Shrinks group membership.",
            "For group members other than the current user",
            "Tell the user to use the Remove button on the member row they want to drop.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Messaging - Agent to Agent",
            "Group settings modal",
            "Leave group",
            "Danger button",
            "Bottom-left of group settings modal",
            "Removes the current user from the group.",
            "Lets the user exit the conversation.",
            "Group settings modal",
            "Tell the user to use 'Leave group' only if they want to exit the group chat.",
            "client/src/pages/Messaging/AgentChat.jsx",
        ),
        (
            "Accounts",
            "Page head",
            "+ Generate login link",
            "Primary button",
            "Top-right of page head",
            "Starts invite generation.",
            "Creates a single-use signup link for a new user.",
            "Accounts page",
            "Tell the admin to use the top-right '+ Generate login link' button.",
            "client/src/pages/Accounts/AccountsPage.jsx",
        ),
        (
            "Accounts",
            "New-link card",
            "Copy",
            "Button",
            "Right side of generated-link field",
            "Copies the newest generated invite link.",
            "Makes sharing easier.",
            "Only after a new invite link has been generated",
            "Tell the admin to use the Copy button beside the generated link field.",
            "client/src/pages/Accounts/AccountsPage.jsx",
        ),
        (
            "Accounts",
            "Accounts table",
            "Account row",
            "Clickable row",
            "Main accounts table",
            "Represents one user account.",
            "Opens the account details modal.",
            "When accounts exist",
            "Tell the admin to click the row for the account they want to inspect.",
            "client/src/pages/Accounts/AccountsPage.jsx",
        ),
        (
            "Accounts",
            "Accounts table",
            "Deactivate / Activate",
            "Menu action",
            "Inside an account row options menu",
            "Toggles whether the account can sign in.",
            "Controls account status without deleting it.",
            "For accounts other than the current admin",
            "Tell the admin to open the row options menu and choose Activate or Deactivate.",
            "client/src/pages/Accounts/AccountsPage.jsx",
        ),
        (
            "Accounts",
            "Accounts table",
            "Delete account",
            "Danger menu action",
            "Inside an account row options menu",
            "Soft-deletes the selected account.",
            "Removes login access for that account.",
            "For accounts other than the current admin",
            "Tell the admin to open the row options menu and choose Delete only after confirming the target user.",
            "client/src/pages/Accounts/AccountsPage.jsx",
        ),
        (
            "Accounts",
            "Invite links table",
            "Copy link / Delete",
            "Action buttons",
            "Right side of each unused invite row",
            "Copies or removes an unused invite link.",
            "Manages pending invites.",
            "For unused invite links",
            "Tell the admin to use the actions at the far right of the invite row.",
            "client/src/pages/Accounts/AccountsPage.jsx",
        ),
        (
            "Accounts",
            "Module access modal",
            "Module checkboxes",
            "Checkbox list",
            "Center of the invite modal body",
            "Selects which modules the invitee can access after signup.",
            "Limits user permissions through the invite link.",
            "When generating a login link",
            "Tell the admin to tick the modules they want the invitee to receive before confirming.",
            "client/src/pages/Accounts/AccountsPage.jsx",
        ),
        (
            "Accounts",
            "Module access modal",
            "Confirm",
            "Primary button",
            "Bottom-right of module access modal",
            "Generates the single-use signup link.",
            "Creates the invite after module selection.",
            "When at least one module is selected",
            "Tell the admin to click 'Confirm' at the bottom of the modal.",
            "client/src/pages/Accounts/AccountsPage.jsx",
        ),
        (
            "User Profile",
            "Hero card",
            "Avatar button",
            "Button",
            "Top-left area of the profile page hero card",
            "Opens the avatar crop and upload flow.",
            "Lets the user change their profile photo.",
            "Profile page",
            "Tell the user to click their avatar in the profile hero card.",
            "client/src/pages/Profile/ProfilePage.jsx",
        ),
        (
            "User Profile",
            "Account details card",
            "Save changes",
            "Primary button",
            "Bottom of account details form",
            "Persists edited name and email.",
            "Updates the user's profile details.",
            "Profile page",
            "Tell the user to click 'Save changes' after editing the account details fields.",
            "client/src/pages/Profile/ProfilePage.jsx",
        ),
        (
            "User Profile",
            "Account details card",
            "Change password",
            "Secondary button",
            "Bottom of account details form",
            "Opens the password change flow.",
            "Takes the user to the multi-step change-password screen.",
            "Profile page",
            "Tell the user to click 'Change password' in the account details card.",
            "client/src/pages/Profile/ProfilePage.jsx",
        ),
        (
            "User Profile",
            "Avatar crop dialog",
            "Scale / Reset position / Save photo",
            "Slider and buttons",
            "Inside the avatar crop modal",
            "Adjusts the framing of the profile picture before saving.",
            "Fine-tunes the final avatar image.",
            "When the avatar crop dialog is open",
            "Tell the user to adjust Scale, optionally Reset position, then click 'Save photo'.",
            "client/src/pages/Profile/ProfilePage.jsx",
        ),
        (
            "Change Password",
            "Step 1",
            "Continue",
            "Primary button",
            "Bottom of the current-password form",
            "Verifies the current password and starts the email-code flow.",
            "Moves the user to step 2.",
            "Current-password stage",
            "Tell the user to enter their current password and click 'Continue'.",
            "client/src/pages/Profile/ChangePasswordPage.jsx",
        ),
        (
            "Change Password",
            "Step 2",
            "Enter code",
            "Primary button",
            "Middle of the stage card",
            "Opens the verification-code modal.",
            "Lets the user input the emailed code.",
            "Email-code stage",
            "Tell the user to click 'Enter code' after checking their email.",
            "client/src/pages/Profile/ChangePasswordPage.jsx",
        ),
        (
            "Change Password",
            "Verification code modal",
            "Verification code",
            "Input",
            "Center of the modal body",
            "Captures the 6-digit code.",
            "Verifies identity before allowing a new password.",
            "When the code modal is open",
            "Tell the user to enter the 6-digit code in the code field.",
            "client/src/pages/Profile/ChangePasswordPage.jsx",
        ),
        (
            "Change Password",
            "Verification code modal",
            "Resend code",
            "Link-style button",
            "Below the code field in the modal",
            "Sends a fresh verification code email.",
            "Restarts the email-code step.",
            "When the code modal is open",
            "Tell the user to use 'Resend code' under the code input if the original code did not arrive.",
            "client/src/pages/Profile/ChangePasswordPage.jsx",
        ),
        (
            "Change Password",
            "Step 3",
            "Update password",
            "Primary button",
            "Bottom of the new-password form",
            "Saves the new password.",
            "Completes the password change.",
            "New-password stage",
            "Tell the user to fill both new password fields and press 'Update password'.",
            "client/src/pages/Profile/ChangePasswordPage.jsx",
        ),
    ],
)


PLAYBOOK_COLUMNS = [
    "User Intent",
    "Best Destination",
    "Where It Lives",
    "Guidance To Give",
    "Caveats",
]
PLAYBOOK_ROWS = make_rows(
    PLAYBOOK_COLUMNS,
    [
        (
            "Change the active Facebook page",
            "Switch Page",
            "Bottom-left sidebar page card",
            "Tell the user to click 'Switch Page' in the sidebar footer, then click the page row they want inside the modal.",
            "Admins can also refresh page data or fix expired pages from the same modal.",
        ),
        (
            "Upload a new post",
            "Upload Post",
            "Left sidebar -> Upload, or page-head shortcut buttons",
            "Tell the user they can open Upload from the left sidebar, or use '+ Upload post' on Dashboard or Post Pool.",
            "Upload is page-scoped, so it uses the currently active page.",
        ),
        (
            "Schedule content for a specific calendar day",
            "Content Calendar",
            "Left sidebar -> Content Calendar",
            "Tell the user to open Content Calendar, click the date cell, then use 'Create Post' in the day planner modal.",
            "Past dates cannot create future posts from the day planner.",
        ),
        (
            "Add planning notes without creating a post",
            "Day planner modal",
            "Content Calendar -> click a day cell",
            "Tell the user to open the day, click 'Add note', write the plan, then save it in the day modal.",
            "Notes can later be dragged to another day with the grip handle.",
        ),
        (
            "See analytics for a page",
            "Analytics",
            "Left sidebar -> Analytics",
            "Tell the user to open Analytics and use the range buttons in the top-right to switch between 7, 28, and 90 days.",
            "Analytics follows the currently active page.",
        ),
        (
            "Edit or delete a post",
            "Post Pool",
            "Left sidebar -> Post Pool",
            "Tell the user to open Post Pool, find the target card, open its card menu, then choose Edit or Delete.",
            "The status filter chips above the grid can help narrow the list first.",
        ),
        (
            "See why posting failed",
            "Posting Logs",
            "Left sidebar -> Logs",
            "Tell the user to open Logs and review the status and message columns for the failed attempt.",
            "Dashboard -> View logs is a shortcut into the same screen.",
        ),
        (
            "Manage scheduling rules or alert emails",
            "Settings - Posting",
            "Left sidebar -> Settings -> Posting",
            "Tell the user to open Settings, stay on the Posting section, change the relevant fields, then click 'Save settings'.",
            "Scheduled publishing is the main automation toggle.",
        ),
        (
            "Connect a Facebook page or Telegram bot",
            "Settings - Pages",
            "Left sidebar -> Settings -> Pages",
            "Tell the user to open Settings, switch to Pages, then use '+ Connect page' or a page card's options menu.",
            "The primary button is two-step: it tests first, then saves after verification succeeds.",
        ),
        (
            "Manage reusable video templates",
            "Settings - Templates",
            "Left sidebar -> Settings -> Templates",
            "Tell the user to open Settings, switch to Templates, then add or edit template JSON from that section.",
            "This section may only appear when the templates feature flag is enabled.",
        ),
        (
            "Reply to a customer",
            "Messaging - Agent to Customer",
            "Left sidebar -> Messaging -> customer mode",
            "Tell the user to open Messaging, stay in Agent to Customer mode, select the conversation from the left, then use the bottom composer if it is a live-agent thread.",
            "If the thread is AI-handled, the user must take it over first.",
        ),
        (
            "Take over an AI conversation",
            "Messaging - locked composer",
            "Customer thread bottom area",
            "Tell the user to open the AI-handled thread and click 'Take over conversation' in the bottom locked composer area.",
            "The UI states this action cannot be reverted or restored.",
        ),
        (
            "Transfer a live customer conversation to another teammate",
            "Messaging - Transfer modal",
            "Customer thread header top-right",
            "Tell the user to open the live-agent thread, click the transfer icon in the upper-right of the thread header, then choose the teammate in the modal.",
            "Transfer is only available for live-agent threads assigned to the current user.",
        ),
        (
            "Message a teammate or create a group chat",
            "Messaging - Agent to Agent",
            "Messaging page left mode rail -> Agent to Agent",
            "Tell the user to switch the messaging mode rail to Agent to Agent, then use search for a DM or 'New group' for a group chat.",
            "Direct replies may be blocked until the two teammates are connected.",
        ),
        (
            "Find or reuse shared files",
            "Vault",
            "Left sidebar -> Vault",
            "Tell the user to open Vault, use the search/filter toolbar if needed, and then open the folder or file card they need.",
            "The same Vault is used by messaging attachment pickers.",
        ),
        (
            "Invite a new teammate",
            "Accounts",
            "Left sidebar -> Accounts",
            "Tell the admin to open Accounts, click '+ Generate login link', select modules in the modal, and confirm to create a single-use signup link.",
            "Accounts is admin-only.",
        ),
        (
            "Change profile details or password",
            "User Profile",
            "Sidebar footer account menu -> User Profile",
            "Tell the user to open the account menu, go to User Profile, then either save edits there or click 'Change password' to enter the multi-step password flow.",
            "Password change requires current-password verification and an emailed code.",
        ),
        (
            "Switch between dark and light theme",
            "User menu",
            "Bottom-left account menu",
            "Tell the user to open the account menu from the sidebar footer and click the theme toggle item.",
            "The label changes based on the current theme.",
        ),
    ],
)


SHEETS = [
    ("0_README", README_ROWS, README_COLUMNS, "244E68"),
    ("1_Navigation", NAVIGATION_ROWS, NAVIGATION_COLUMNS, "1C6A8C"),
    ("2_Screens", SCREEN_ROWS, SCREEN_COLUMNS, "2A7F62"),
    ("3_Controls", CONTROL_ROWS, CONTROL_COLUMNS, "805B2B"),
    ("4_Assistant Playbook", PLAYBOOK_ROWS, PLAYBOOK_COLUMNS, "6E4AA3"),
]


WIDTHS = {
    "0_README": {"A": 24, "B": 120},
    "1_Navigation": {"A": 22, "B": 24, "C": 18, "D": 30, "E": 30, "F": 34, "G": 22, "H": 40, "I": 42},
    "2_Screens": {"A": 24, "B": 24, "C": 28, "D": 34, "E": 46, "F": 38, "G": 22, "H": 24, "I": 42},
    "3_Controls": {"A": 24, "B": 22, "C": 30, "D": 16, "E": 30, "F": 24, "G": 30, "H": 28, "I": 42, "J": 42},
    "4_Assistant Playbook": {"A": 34, "B": 22, "C": 28, "D": 52, "E": 34},
}


HEADER_FILL = PatternFill("solid", fgColor="17384D")
HEADER_FONT = Font(color="FFFFFF", bold=True)
BODY_ALIGNMENT = Alignment(vertical="top", wrap_text=True)
HEADER_ALIGNMENT = Alignment(vertical="center", horizontal="center", wrap_text=True)
THIN_BORDER = Border(
    left=Side(style="thin", color="D7DEE5"),
    right=Side(style="thin", color="D7DEE5"),
    top=Side(style="thin", color="D7DEE5"),
    bottom=Side(style="thin", color="D7DEE5"),
)


def write_sheet(ws, rows, headers, tab_color):
    ws.sheet_view.showGridLines = False
    ws.sheet_properties.tabColor = tab_color
    ws.append(headers)
    for row in rows:
        ws.append([row.get(header, "") for header in headers])

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions

    for cell in ws[1]:
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = HEADER_ALIGNMENT
        cell.border = THIN_BORDER

    for row in ws.iter_rows(min_row=2):
        for cell in row:
            cell.alignment = BODY_ALIGNMENT
            cell.border = THIN_BORDER

    ws.row_dimensions[1].height = 28
    for col, width in WIDTHS.get(ws.title, {}).items():
        ws.column_dimensions[col].width = width


def build_workbook():
    wb = Workbook()
    first = True
    for title, rows, headers, color in SHEETS:
        if first:
            ws = wb.active
            ws.title = title
            first = False
        else:
            ws = wb.create_sheet(title)
        write_sheet(ws, rows, headers, color)

    wb.properties.title = "Wise Assistant Layout Context"
    wb.properties.subject = "Navigation and UI dictionary for pwise"
    wb.properties.creator = "Codex"
    wb.properties.description = (
        "Structured navigation, screen, control, and assistant guidance context "
        "for the pwise web app."
    )
    return wb


def main():
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    wb = build_workbook()
    wb.save(OUTPUT_PATH)
    print(f"Created {OUTPUT_PATH}")
    for title, rows, _, _ in SHEETS:
        print(f"{title}: {len(rows)} data rows")


if __name__ == "__main__":
    main()
