-- AI Agent vector store (Supabase Postgres + pgvector).
--
-- Holds OpenAI embeddings of the MySQL `products` and `ai_agent_reference`
-- tables, synced by scripts/src/sync-agent-vectors.js. The shape follows the
-- n8n "Supabase Vector Store" / LangChain contract so the node can read it:
--   content (text) + metadata (jsonb) + embedding (vector) + a match function.
--
-- Run this ONCE in the Supabase SQL editor. (The sync script also applies it
-- idempotently on each run, so this is mainly for first-time setup / reference.)
--
-- EMBEDDING MODEL: OpenAI text-embedding-3-small => 1536 dimensions. If you ever
-- switch models you MUST change every vector(1536) below, re-run the sync, and
-- use the SAME model in n8n at query time — otherwise similarity is meaningless.

create extension if not exists vector;

create table if not exists public.agent_documents (
  id           bigint generated by default as identity primary key,
  source       text not null,                       -- 'products' | 'ai_agent_reference'
  source_id    text not null,                        -- the MySQL row's primary key, as text
  content      text not null,                        -- the exact text that was embedded
  metadata     jsonb not null default '{}'::jsonb,   -- the full source row + source/source_id
  embedding    vector(1536),                         -- OpenAI text-embedding-3-small
  content_hash text not null,                        -- sha256(content): drives re-embedding
  meta_hash    text not null,                        -- sha256(metadata): drives metadata-only refresh
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (source, source_id)                          -- upsert + dedup key
);

-- Approximate-nearest-neighbour index for cosine similarity searches.
-- (HNSW needs pgvector >= 0.5.0, which Supabase provides. On older pgvector use
--  ivfflat: create index ... using ivfflat (embedding vector_cosine_ops) with (lists = 100);)
create index if not exists idx_agent_documents_embedding
  on public.agent_documents using hnsw (embedding vector_cosine_ops);

-- Lets the agent filter by metadata, e.g. {"source":"products"}.
create index if not exists idx_agent_documents_metadata
  on public.agent_documents using gin (metadata);

create index if not exists idx_agent_documents_source
  on public.agent_documents (source);

-- Retrieval function the n8n Supabase Vector Store node calls ("Query Name").
-- Signature mirrors LangChain's SupabaseVectorStore: (query_embedding, match_count, filter).
create or replace function public.match_agent_documents (
  query_embedding vector(1536),
  match_count int default 5,
  filter jsonb default '{}'::jsonb
) returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language plpgsql
as $$
begin
  return query
  select
    d.id,
    d.content,
    d.metadata,
    1 - (d.embedding <=> query_embedding) as similarity
  from public.agent_documents d
  where d.metadata @> filter
  order by d.embedding <=> query_embedding
  limit match_count;
end;
$$;
