-- =====================================================================
-- Auto Post Agent — database schema (MySQL 8.0+)
-- Idempotent: safe to run multiple times. Apply with `npm run db:migrate`.
--
-- Notes / deviations from the original plan:
--   * Engine InnoDB, charset utf8mb4 — captions contain emojis, and utf8mb4
--     is required to store 4-byte characters.
--   * Timestamps are DATETIME storing UTC (the app converts to each user's
--     `timezone`). created_at/updated_at use DEFAULT CURRENT_TIMESTAMP +
--     ON UPDATE CURRENT_TIMESTAMP, so MySQL maintains updated_at natively
--     (no trigger needed).
--   * status / media_type use CHECK constraints (enforced on MySQL 8.0.16+).
--   * Foreign keys are table-level — MySQL silently ignores inline column
--     REFERENCES, so they must be declared as constraints.
--   * posting_settings.user_id is UNIQUE (one settings row per user); the
--     post_pool index matches the scheduler's claim query.
-- =====================================================================

-- access_roles — named module-access presets ("User Roles"). Defined before
-- users/invites because both carry an FK to it. `created_by` is audit-only (no FK)
-- so this table depends on nothing and can lead the file. Named access_roles (not
-- `roles`) to avoid confusion with the users.role auth column.
CREATE TABLE IF NOT EXISTS access_roles (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  name          VARCHAR(80) NOT NULL,
  module_access JSON NOT NULL,
  created_by    INT NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_access_roles_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- users — account information -------------------------------------------
CREATE TABLE IF NOT EXISTS users (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  name          VARCHAR(255) NOT NULL,
  email         VARCHAR(255) NOT NULL,
  password_hash TEXT NOT NULL,
  role          VARCHAR(20) NOT NULL DEFAULT 'user',
  module_access JSON NULL,
  role_id       INT NULL,                     -- live link to an access_roles preset (NULL = Custom)
  avatar_s3_key TEXT NULL,
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  -- Brute-force lockout: incremented on each wrong password, reset on success.
  -- When it reaches the limit, locked_until is set (UTC) and new logins are refused
  -- until it passes (lazy auto-unlock) or an admin clears it from Accounts.
  failed_login_attempts INT NOT NULL DEFAULT 0,
  locked_until  DATETIME NULL,
  deleted_at    DATETIME NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_users_email (email),
  CONSTRAINT chk_users_role CHECK (role IN ('super_admin', 'admin', 'user')),
  CONSTRAINT fk_users_access_role FOREIGN KEY (role_id) REFERENCES access_roles(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- invites — single-use sign-up links generated by admins -----------------
CREATE TABLE IF NOT EXISTS invites (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  token       VARCHAR(64) NOT NULL,
  created_by  INT NOT NULL,                 -- the admin who generated the link
  module_access JSON NULL,                  -- selected feature modules granted by the link
  role_id     INT NULL,                     -- optional access_roles preset this link binds to
  used_by     INT NULL,                     -- the account created with it
  used_at     DATETIME NULL,
  expires_at  DATETIME NULL,                -- optional; NULL = no time limit
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_invites_token (token),
  CONSTRAINT fk_invites_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_invites_user FOREIGN KEY (used_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_invites_access_role FOREIGN KEY (role_id) REFERENCES access_roles(id) ON DELETE SET NULL,
  INDEX idx_invites_creator (created_by)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- password_change_codes — email-verified password changes (one pending per user)
CREATE TABLE IF NOT EXISTS password_change_codes (
  user_id    INT NOT NULL PRIMARY KEY,
  code_hash  VARCHAR(255) NOT NULL,
  expires_at DATETIME NOT NULL,
  verified   BOOLEAN NOT NULL DEFAULT FALSE,
  attempts   INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pcc_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- auth_otp_codes — generic one-time email codes for sensitive auth actions
-- (purpose='login' for the new-device login OTP, 'email_change' for changing the
-- account email). One pending code per (user_id, purpose); a fresh request replaces
-- the previous one. Mirrors password_change_codes (bcrypt-hashed code, TTL, attempt
-- cap). payload carries action data (e.g. the pending new email for 'email_change').
CREATE TABLE IF NOT EXISTS auth_otp_codes (
  user_id    INT NOT NULL,
  purpose    VARCHAR(20) NOT NULL,
  code_hash  VARCHAR(255) NOT NULL,
  expires_at DATETIME NOT NULL,
  verified   BOOLEAN NOT NULL DEFAULT FALSE,
  attempts   INT NOT NULL DEFAULT 0,
  payload    JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, purpose),
  CONSTRAINT fk_otp_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- trusted_devices — a browser the user chose to trust ("Trust this device"), so
-- future logins from it skip the email OTP. The server issues a high-entropy secret
-- and stores only its SHA-256 (token_hash); the raw secret lives in the client's
-- localStorage. A trusted device only bypasses the OTP — it NEVER bypasses the
-- password — so a stolen token alone can't log in. Sliding 30-day expiry; revoked
-- on "log out all other devices" and on password change.
CREATE TABLE IF NOT EXISTS trusted_devices (
  id           INT AUTO_INCREMENT PRIMARY KEY,
  user_id      INT NOT NULL,
  token_hash   CHAR(64) NOT NULL,
  label        VARCHAR(255) NULL,
  ip           VARCHAR(64) NULL,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_used_at DATETIME NULL,
  expires_at   DATETIME NOT NULL,
  revoked_at   DATETIME NULL,
  UNIQUE KEY uq_trusted_devices_token (token_hash),
  CONSTRAINT fk_trusted_devices_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_trusted_devices_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- login_history — login sessions: one row per successful login = a revocable
-- "session". The JWT carries this row's id (sid); requireAuth rejects a token whose
-- session row is missing or has revoked_at set (this is what powers "log out of this
-- device" / "all other devices"). last_seen_at is bumped (throttled) on activity, and
-- the same rows back the Profile → Security list. Deleting a user drops their sessions.
CREATE TABLE IF NOT EXISTS login_history (
  id           INT AUTO_INCREMENT PRIMARY KEY,
  user_id      INT NOT NULL,
  ip           VARCHAR(64) NULL,
  user_agent   VARCHAR(512) NULL,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at DATETIME NULL,
  revoked_at   DATETIME NULL,
  CONSTRAINT fk_login_history_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_login_history_user (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- post_pool — uploaded post content (the pool the agent draws from) ------
CREATE TABLE IF NOT EXISTS post_pool (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  user_id         INT NOT NULL,
  caption         TEXT,
  media_type      VARCHAR(50),
  post_kind       VARCHAR(20) NOT NULL DEFAULT 'post',  -- 'post' (text/photo) | 'video' (feed video) | 'reel'; orthogonal to media_type
  media_url       TEXT,
  s3_key          TEXT,
  thumbnail_s3_key TEXT,                       -- optimized still (first video frame / downscaled image) for previews
  target_platform VARCHAR(100),
  account_id      INT NULL,                    -- which connected page this post publishes to
  status          VARCHAR(50) NOT NULL DEFAULT 'draft',
  priority        INT NOT NULL DEFAULT 0,
  scheduled_at    DATETIME NULL,
  posted_at       DATETIME NULL,
  failed_reason   TEXT,
  -- Engagement pulled back from the platform by the n8n sync flow:
  platform_post_id     VARCHAR(255) NULL,   -- published post's ID on the platform (e.g. {page}_{post})
  reactions_count      INT NULL,
  comments_count       INT NULL,
  shares_count         INT NULL,
  views_count          INT NULL,            -- video/reel views (NULL for image/text)
  video_watch_time_s   INT NULL,            -- total watch time across all views, in seconds (video only)
  video_avg_watch_s    INT NULL,            -- average time watched per view, in seconds (video only)
  engagement_synced_at DATETIME NULL,       -- last time engagement was refreshed
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_post_pool_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_post_pool_account FOREIGN KEY (account_id) REFERENCES platform_accounts(id) ON DELETE SET NULL,
  CONSTRAINT chk_post_pool_status
    CHECK (status IN ('draft','ready','posting','posted','failed','archived','expired','deleted')),
  CONSTRAINT chk_post_pool_media_type
    CHECK (media_type IS NULL OR media_type IN ('image','video')),
  -- post_kind picks the publish path: 'post' → /feed or /photos, 'video' → /videos, 'reel' → /video_reels.
  CONSTRAINT chk_post_pool_kind
    CHECK (post_kind IN ('post','video','reel')),
  -- Supports the scheduler claim query:
  --   WHERE user_id = ? AND status = 'ready'
  --   ORDER BY priority DESC, created_at ASC  ... FOR UPDATE SKIP LOCKED LIMIT 1
  INDEX idx_post_pool_claim (user_id, status, priority DESC, created_at),
  INDEX idx_post_pool_account (account_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- posting_settings — automation config (exactly one row per user) --------
CREATE TABLE IF NOT EXISTS posting_settings (
  id                       INT AUTO_INCREMENT PRIMARY KEY,
  user_id                  INT NOT NULL,
  is_enabled               BOOLEAN NOT NULL DEFAULT FALSE,
  timezone                 VARCHAR(100) NOT NULL DEFAULT 'Asia/Manila',
  low_pool_alert_threshold INT NOT NULL DEFAULT 3,
  owner_email              VARCHAR(255),
  last_alert_sent_at       DATETIME NULL,
  selected_account_id      INT NULL,            -- this user's currently-active page
  created_at               DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at               DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_posting_settings_user (user_id),
  CONSTRAINT fk_posting_settings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_posting_settings_account FOREIGN KEY (selected_account_id) REFERENCES platform_accounts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- posting_logs — every posting attempt (append-only; no updated_at) ------
CREATE TABLE IF NOT EXISTS posting_logs (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  user_id          INT NOT NULL,
  post_id          INT NULL,
  target_platform  VARCHAR(100),
  status           VARCHAR(50),
  response_message TEXT,
  error_message    TEXT,
  posted_at        DATETIME NULL,
  created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_posting_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_posting_logs_post FOREIGN KEY (post_id) REFERENCES post_pool(id) ON DELETE SET NULL,
  INDEX idx_posting_logs_user (user_id, created_at DESC),
  INDEX idx_posting_logs_post (post_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- platform_accounts — connected posting channels (Facebook pages) -------
-- Sensitive credentials (app_secret, app_client_token, access_token) MUST be
-- encrypted before being written here — see server/src/utils/crypto.util.js.
-- The page list is shared/global; user_id records the admin creator (audit).
CREATE TABLE IF NOT EXISTS platform_accounts (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  user_id          INT NOT NULL,
  platform_name    VARCHAR(100) NOT NULL,
  account_name     VARCHAR(255),                -- page display name
  fb_page_id       VARCHAR(255),                -- Facebook Page ID
  app_id           VARCHAR(255),                -- Facebook App ID (not secret)
  app_secret       TEXT,                        -- ENCRYPTED
  app_client_token TEXT,                        -- ENCRYPTED
  access_token     TEXT,                        -- ENCRYPTED page access token
  telegram_bot_name     VARCHAR(255),           -- optional Telegram bot attached to this page
  telegram_bot_token    TEXT,                   -- ENCRYPTED Telegram bot API key
  telegram_bot_username VARCHAR(255),           -- Telegram bot @username (from getMe)
  -- Optional Instagram + WhatsApp channels on this page (migration 040). IG reuses the
  -- page access_token; WhatsApp has its own encrypted token + phone number id.
  instagram_account_id   VARCHAR(64)  NULL,      -- IG professional account id
  instagram_username     VARCHAR(255) NULL,
  wa_phone_number_id     VARCHAR(64)  NULL,      -- WhatsApp Cloud API phone number id
  wa_business_account_id VARCHAR(64)  NULL,      -- WABA id
  wa_phone_display       VARCHAR(40)  NULL,      -- human number for display
  wa_access_token        TEXT         NULL,      -- ENCRYPTED WhatsApp system-user token
  -- Per-page "Business profile" (migration 042) — admin-filled contact / location /
  -- hours, surfaced to the AI agent via its get_page_info tool. One JSON object; every
  -- field optional. NULL = no profile yet.
  business_profile JSON NULL,
  -- Customer-survey settings (migration 058) — { enabled, chancePct, cooldownDays }.
  -- NULL = defaults (disabled). Admin-edited in Settings → Facebook Pages.
  survey_config    JSON NULL,
  -- Per-page survey email sender (migration 061). The app password is ENCRYPTED.
  survey_sender_email VARCHAR(255) NULL,
  survey_sender_name VARCHAR(255) NULL,
  survey_sender_app_password TEXT NULL,
  refresh_token    TEXT,                        -- ENCRYPTED (reserved)
  token_expires_at DATETIME NULL,
  is_active        BOOLEAN NOT NULL DEFAULT TRUE,
  created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_platform_accounts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_platform_accounts_user (user_id, platform_name),
  INDEX idx_pa_instagram (instagram_account_id),
  INDEX idx_pa_whatsapp (wa_phone_number_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- post_activity_log — audit trail of who created/edited/deleted each post -----
-- (the pool is shared; this identifies the actor). user/post SET NULL on delete
-- so the record survives; user_name is a snapshot for durable display.
CREATE TABLE IF NOT EXISTS post_activity_log (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  post_id    INT NULL,
  user_id    INT NULL,
  user_name  VARCHAR(255),
  note_id    INT NULL,                      -- set instead of post_id for content-note actions
  action     VARCHAR(20) NOT NULL,
  details    TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_activity_post FOREIGN KEY (post_id) REFERENCES post_pool(id) ON DELETE SET NULL,
  CONSTRAINT fk_activity_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_activity_action CHECK (action IN ('created','edited','deleted','tagged')),
  INDEX idx_activity_created (created_at DESC),
  INDEX idx_activity_post (post_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- content_notes — per-day content planning behind the calendar -----------------
-- Each row is one planning note attached to a calendar day. Shared pool (every
-- signed-in user sees/edits all notes); user_id/user_name record the author.
-- The calendar is a GENERAL (page-independent) view, so page_id records which
-- connected page owns the note (drives the page logo on each calendar note row).
CREATE TABLE IF NOT EXISTS content_notes (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  note_date  DATE NOT NULL,
  content    TEXT NOT NULL,
  status     VARCHAR(20) NOT NULL DEFAULT 'pending',  -- pending | ongoing | completed | cancelled
  position   INT NOT NULL DEFAULT 0,                   -- rank within the day (drag-to-reorder)
  text_color VARCHAR(9) NULL,                          -- optional hex (#RRGGBB[AA]) text override
  note_color VARCHAR(9) NULL,                          -- optional hex (#RRGGBB[AA]) background override
  page_id    INT NULL,                                 -- owning page (NULL = untagged); logo on the calendar row
  user_id    INT NULL,
  user_name  VARCHAR(255),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_content_notes_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_content_notes_page FOREIGN KEY (page_id) REFERENCES platform_accounts(id) ON DELETE SET NULL,
  CONSTRAINT chk_content_notes_status CHECK (status IN ('pending','ongoing','completed','cancelled')),
  INDEX idx_content_notes_date (note_date),
  INDEX idx_content_notes_date_pos (note_date, position),
  INDEX idx_content_notes_page (page_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- post_insight_history — one engagement snapshot per post per HOUR ------------
-- Facebook returns only current totals, so we record snapshots (pulled during
-- the engagement refresh and by the scheduled snapshot job) to plot insights
-- over time. Forward-only. captured_at is truncated to the hour; Day/Month
-- views aggregate the hourly points.
CREATE TABLE IF NOT EXISTS post_insight_history (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  post_id         INT NOT NULL,
  captured_at     DATETIME NOT NULL,
  reactions_count INT NULL,
  comments_count  INT NULL,
  shares_count    INT NULL,
  views_count     INT NULL,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_insight_post_hour (post_id, captured_at),
  CONSTRAINT fk_insight_post FOREIGN KEY (post_id) REFERENCES post_pool(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- post_comment_status — team-shared "handled" state for the Comments inbox ------
-- The Comments view (Contents → Comments) aggregates live Facebook comments across
-- a page's posts. Comment CONTENT is never stored (always read live from Graph); this
-- table stores ONLY the tracking state so every teammate on a page sees the same
-- handled/unhandled list. A row present with status='done' = handled; un-marking a
-- comment deletes its row (absence = open). Enum kept for future states (follow-up).
CREATE TABLE IF NOT EXISTS post_comment_status (
  account_id      INT NOT NULL,                    -- connected page the comment belongs to
  comment_id      VARCHAR(255) NOT NULL,           -- Facebook comment id (globally unique)
  post_id         INT NULL,                        -- post_pool.id the comment is on (for context)
  status          ENUM('open','done') NOT NULL DEFAULT 'done',
  handled_by_id   INT NULL,
  handled_by_name VARCHAR(255) NULL,
  handled_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (account_id, comment_id),
  KEY idx_pcs_status (account_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- page_insight_daily — daily page-level metrics (Analytics dashboard) ----------
-- Generic metric/value-by-day: reach, impressions, post reach, engagement,
-- follows, unfollows. Backfilled from the Graph Insights API, refreshed forward.
CREATE TABLE IF NOT EXISTS page_insight_daily (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  account_id  INT NULL,                          -- which connected page (NULL = legacy/env)
  captured_on DATE NOT NULL,
  metric      VARCHAR(64) NOT NULL,
  value       BIGINT NOT NULL DEFAULT 0,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_page_insight_acct_day_metric (account_id, captured_on, metric),
  INDEX idx_page_insight_acct_metric (account_id, metric, captured_on)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- creatomate_templates — reusable video render configs (Settings) --------------
CREATE TABLE IF NOT EXISTS creatomate_templates (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(255) NOT NULL,
  config      LONGTEXT NOT NULL,
  user_id     INT NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_creatomate_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- conversations — customer chat threads per connected page (Messaging inbox) ----
-- Shared/global like the rest of the app: every signed-in user sees all threads.
-- account_id links the page; page_name is a denormalized snapshot for display.
-- handled_by toggles AI Agent vs Live Agent; unread is the chat-level unseen count.
CREATE TABLE IF NOT EXISTS conversations (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  account_id      INT NULL,
  page_name       VARCHAR(255),
  customer_name   VARCHAR(255) NOT NULL,
  customer_handle VARCHAR(255),
  customer_avatar TEXT,
  origin          VARCHAR(50),                              -- Messenger | Instagram | WhatsApp | Telegram
  handled_by      VARCHAR(20) NOT NULL DEFAULT 'AI Agent',  -- 'AI Agent' | 'Live Agent'
  assigned_user_id   INT NULL,                              -- owner when handled by a Live Agent
  assigned_user_name VARCHAR(255),                          -- snapshot for display
  status          VARCHAR(80),
  tags            JSON NULL,
  summary         TEXT,
  unread          INT NOT NULL DEFAULT 0,
  blocked         TINYINT(1) NOT NULL DEFAULT 0,            -- block the customer (drops inbound + n8n)
  blocked_at      DATETIME NULL,
  blocked_by      INT NULL,                                 -- Live Agent user id (NULL when the AI blocked)
  blocked_by_name VARCHAR(255) NULL,                        -- snapshot: agent name, or 'AI Agent'
  last_message_at DATETIME NULL,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_conversations_account FOREIGN KEY (account_id) REFERENCES platform_accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_conversations_assignee FOREIGN KEY (assigned_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_conversations_handled CHECK (handled_by IN ('AI Agent', 'Live Agent')),
  INDEX idx_conversations_account (account_id, last_message_at),
  INDEX idx_conversations_activity (last_message_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- messages — individual bubbles within a conversation -------------------------
-- Messenger-style: a bubble holds text OR media (never both). media/reply_to are
-- JSON; body is the text. created_at drives both ordering and the displayed time.
CREATE TABLE IF NOT EXISTS messages (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  conversation_id INT NOT NULL,
  side            VARCHAR(10) NOT NULL,                     -- 'incoming' | 'outgoing'
  sender          VARCHAR(255),
  body            TEXT NULL,
  media           JSON NULL,                                -- [{ type, url, name }]
  reply_to        JSON NULL,                                -- { id, sender, text }
  external_id     VARCHAR(255) NULL,                         -- platform message id (Telegram message_id, Messenger/IG mid, WhatsApp wamid), for reply threading + delivery status
  delivery_status VARCHAR(16) NULL,                          -- NULL = n/a · 'sent' · 'failed' (outgoing platform delivery)
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
  CONSTRAINT chk_messages_side CHECK (side IN ('incoming', 'outgoing')),
  INDEX idx_messages_conversation (conversation_id, created_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- agent-to-agent chat — internal DMs + group chats between teammates
CREATE TABLE IF NOT EXISTS agent_conversations (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  is_group        TINYINT(1) NOT NULL DEFAULT 0,
  name            VARCHAR(255) NULL,                 -- group name (NULL for DMs)
  created_by      INT NULL,
  last_message_at DATETIME NULL,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_agent_conv_activity (last_message_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_conversation_participants (
  conversation_id INT NOT NULL,
  user_id         INT NOT NULL,
  last_read_at    DATETIME NULL,
  joined_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (conversation_id, user_id),
  INDEX idx_agent_part_user (user_id),
  CONSTRAINT fk_agent_part_conv FOREIGN KEY (conversation_id) REFERENCES agent_conversations(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_messages (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  conversation_id INT NOT NULL,
  sender_user_id  INT NULL,
  sender_name     VARCHAR(255),
  body            TEXT NULL,
  media           JSON NULL,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_agent_msg_conv FOREIGN KEY (conversation_id) REFERENCES agent_conversations(id) ON DELETE CASCADE,
  INDEX idx_agent_msg_conv (conversation_id, created_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- connections — agent-to-agent "friend" graph (gates replying in A2A DMs)
CREATE TABLE IF NOT EXISTS user_connections (
  id           INT AUTO_INCREMENT PRIMARY KEY,
  requester_id INT NOT NULL,
  addressee_id INT NOT NULL,
  status       VARCHAR(20) NOT NULL DEFAULT 'pending',  -- pending | accepted
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  responded_at DATETIME NULL,
  UNIQUE KEY uq_connection_pair (requester_id, addressee_id),
  INDEX idx_connection_addressee (addressee_id, status),
  INDEX idx_connection_requester (requester_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- page_products — per-page product catalog (Workspace → Products + the chat
-- composer's Products drawer). Bound to a connected page; the photo is a stable S3
-- key (the API presigns photo_url on read). tags = JSON array of strings.
CREATE TABLE IF NOT EXISTS page_products (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  account_id  INT NOT NULL,
  name        VARCHAR(255) NOT NULL,
  base_price  DECIMAL(12, 2) NULL,
  description TEXT NULL,
  category    VARCHAR(120) NULL,
  tags        JSON NULL,
  options     JSON NULL,                       -- option axes for variants: [{"name","values":[...]}]
  photo_key   VARCHAR(512) NULL,
  created_by  INT NULL,
  updated_by  INT NULL,
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_page_products_account FOREIGN KEY (account_id) REFERENCES platform_accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_page_products_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_page_products_editor  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_page_products_account (account_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- wise_assistant_chats — Rovi's per-user help chat, stored server-side so it
-- follows a user across devices. One row per user; messages JSON = capped
-- [{ role, text }] list (intro greeting excluded, newest last).
CREATE TABLE IF NOT EXISTS wise_assistant_chats (
  user_id    INT NOT NULL PRIMARY KEY,
  messages   JSON NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_wise_chat_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- vault_items — shared file manager (folders + files in one self-referencing tree)
-- Global like the rest of the app: every signed-in user sees/edits all items.
-- Files carry an S3 key (+ optional thumbnail). Folder deletes cascade to children
-- (the app deletes their S3 objects first). user_id = uploader (audit).
CREATE TABLE IF NOT EXISTS vault_items (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  parent_id        INT NULL,                       -- NULL = root ("Main")
  type             VARCHAR(10) NOT NULL,           -- 'folder' | 'file'
  name             VARCHAR(255) NOT NULL,
  media_type       VARCHAR(20),                    -- 'image' | 'video' | 'file' (files only)
  mime_type        VARCHAR(150),
  s3_key           TEXT,                           -- files only
  thumbnail_s3_key TEXT,                           -- optimized still (images/videos)
  size             BIGINT NOT NULL DEFAULT 0,
  user_id          INT NULL,                       -- uploader (audit)
  uploaded_by      VARCHAR(255),                   -- snapshot name for durable display
  created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_vault_parent FOREIGN KEY (parent_id) REFERENCES vault_items(id) ON DELETE CASCADE,
  CONSTRAINT fk_vault_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_vault_type CHECK (type IN ('folder', 'file')),
  INDEX idx_vault_parent (parent_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- vault_folder_access — allow-list for PRIVATE vault folders (migration 045). A private
-- folder (vault_items.visibility='private', a column added in migration 045) plus its
-- whole subtree is visible/accessible only to admins and the users listed here. Public
-- folders (the default) have no rows. Cascades with the folder or the user.
CREATE TABLE IF NOT EXISTS vault_folder_access (
  folder_id INT NOT NULL,
  user_id   INT NOT NULL,
  PRIMARY KEY (folder_id, user_id),
  CONSTRAINT fk_vfa_folder FOREIGN KEY (folder_id) REFERENCES vault_items(id) ON DELETE CASCADE,
  CONSTRAINT fk_vfa_user   FOREIGN KEY (user_id)   REFERENCES users(id)       ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- conversation_transfers — handoff of a Live Agent conversation to another user --
-- The recipient (to_user_id) must accept before ownership (conversations.assigned_user_id)
-- actually moves. One pending transfer per conversation at a time.
CREATE TABLE IF NOT EXISTS conversation_transfers (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  conversation_id INT NOT NULL,
  from_user_id    INT NULL,
  from_user_name  VARCHAR(255),
  to_user_id      INT NOT NULL,
  to_user_name    VARCHAR(255),
  status          VARCHAR(20) NOT NULL DEFAULT 'pending',  -- pending | accepted | declined | cancelled
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  responded_at    DATETIME NULL,
  CONSTRAINT fk_transfer_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE,
  CONSTRAINT fk_transfer_from FOREIGN KEY (from_user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_transfer_to FOREIGN KEY (to_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT chk_transfer_status CHECK (status IN ('pending', 'accepted', 'declined', 'cancelled')),
  INDEX idx_transfer_to_pending (to_user_id, status),
  INDEX idx_transfer_conversation (conversation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- page_product_variants — option-matrix variants for page_products (migration 035).
-- One row per generated combination, each with its own price + photo. A product with
-- no `options` is "simple" and has no variants (uses page_products.base_price).
CREATE TABLE IF NOT EXISTS page_product_variants (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  product_id    INT NOT NULL,
  combo_key     VARCHAR(255) NOT NULL,        -- canonical "Size=1L|Scent=Lemon"
  option_values JSON NOT NULL,                -- {"Size":"1L","Scent":"Lemon"}
  price         DECIMAL(12, 2) NULL,          -- NULL = "Quote" for this combination
  photo_key     VARCHAR(512) NULL,            -- stable S3 key (API presigns on read)
  active        TINYINT(1) NOT NULL DEFAULT 1,
  sort_order    INT NOT NULL DEFAULT 0,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ppv_product FOREIGN KEY (product_id) REFERENCES page_products(id) ON DELETE CASCADE,
  UNIQUE KEY uq_ppv_combo (product_id, combo_key),
  INDEX idx_ppv_product (product_id, sort_order, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- page_discounts — per-page cart discount rules (migration 036). value_type is fixed
-- or percent (with optional percent_cap); scope decides when the rule applies and
-- applies_to whether it discounts the whole order or only qualifying items.
CREATE TABLE IF NOT EXISTS page_discounts (
  id                INT AUTO_INCREMENT PRIMARY KEY,
  account_id        INT NOT NULL,
  name              VARCHAR(255) NOT NULL,
  description       TEXT NULL,
  active            TINYINT(1) NOT NULL DEFAULT 1,
  value_type        ENUM('fixed', 'percent') NOT NULL,
  value             DECIMAL(12, 2) NOT NULL,
  percent_cap       DECIMAL(12, 2) NULL,
  scope             ENUM('all', 'category', 'product', 'cart_item_count', 'product_qty', 'min_order_amount') NOT NULL,
  target_category   VARCHAR(120) NULL,
  target_product_id INT NULL,
  threshold_qty     INT NULL,
  min_amount        DECIMAL(12, 2) NULL,
  applies_to        ENUM('order', 'matching_items') NOT NULL DEFAULT 'order',
  stackable         TINYINT(1) NOT NULL DEFAULT 0,
  priority          INT NOT NULL DEFAULT 0,
  starts_at         DATETIME NULL,
  ends_at           DATETIME NULL,
  code              VARCHAR(60) NULL,
  created_by        INT NULL,
  updated_by        INT NULL,
  created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_pd_account FOREIGN KEY (account_id) REFERENCES platform_accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_pd_product FOREIGN KEY (target_product_id) REFERENCES page_products(id) ON DELETE CASCADE,
  CONSTRAINT fk_pd_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_pd_editor  FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_pd_account (account_id, active, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------
-- Orders, agreements & receipts (migration 049) — the post-cart checkout flow.
-- order_agreements is the IMMUTABLE pre-order snapshot a staff member generates and
-- shares with the customer via an unguessable token (public /agreement/:token); it
-- expires in 30 min and, once the customer confirms, spawns an `orders` row. Orders and
-- receipts are owner-scoped (created_by) with admin bypass.
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_agreements (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  token            CHAR(40) NOT NULL,                   -- crypto-random hex; the public-link capability
  account_id       INT NOT NULL,                        -- page scope
  conversation_id  INT NULL,                            -- chat that produced it (NULL for Shop-only); attribution for sales-per-conversation
  created_by       INT NULL,                            -- owner (staff who drafted it)
  created_by_name  VARCHAR(255) NULL,
  currency         VARCHAR(8) NOT NULL DEFAULT 'PHP',
  customer_name    VARCHAR(255) NOT NULL,
  delivery_address TEXT NOT NULL,
  contact_number   VARCHAR(60) NOT NULL,
  email            VARCHAR(255) NULL,
  notes            TEXT NULL,
  language         VARCHAR(8) NOT NULL DEFAULT 'en',
  items            JSON NOT NULL,                        -- [{productId,variantId,name,variantLabel,unitPrice,quantity,category,media}]
  discounts        JSON NOT NULL,                        -- applied [{id,name,amount}]
  subtotal         DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_discount   DECIMAL(12,2) NOT NULL DEFAULT 0,
  total            DECIMAL(12,2) NOT NULL DEFAULT 0,
  status           ENUM('active','confirmed','expired','cancelled') NOT NULL DEFAULT 'active',
  expires_at       DATETIME NOT NULL,
  first_viewed_at  DATETIME NULL,
  last_viewed_at   DATETIME NULL,
  confirmed_at     DATETIME NULL,
  order_id         INT NULL,                             -- set on confirm (no FK: orders is created after)
  created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_oa_account FOREIGN KEY (account_id) REFERENCES platform_accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_oa_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE SET NULL,
  CONSTRAINT fk_oa_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uq_oa_token (token),
  INDEX idx_oa_account (account_id, created_by, id),
  INDEX idx_oa_conversation (conversation_id),
  INDEX idx_oa_status (status, expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS orders (
  id               INT AUTO_INCREMENT PRIMARY KEY,
  agreement_id     INT NULL,
  account_id       INT NOT NULL,
  conversation_id  INT NULL,                             -- chat that produced it (NULL for Shop-only); attribution for sales-per-conversation
  created_by       INT NULL,                             -- owner (admins bypass)
  created_by_name  VARCHAR(255) NULL,
  currency         VARCHAR(8) NOT NULL DEFAULT 'PHP',
  customer_name    VARCHAR(255) NOT NULL,
  delivery_address TEXT NOT NULL,
  contact_number   VARCHAR(60) NOT NULL,
  email            VARCHAR(255) NULL,
  notes            TEXT NULL,
  subtotal         DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_discount   DECIMAL(12,2) NOT NULL DEFAULT 0,
  total            DECIMAL(12,2) NOT NULL DEFAULT 0,
  status           ENUM('pending','paid','processing','ready_for_pickup','shipped','out_for_delivery','completed','cancelled') NOT NULL DEFAULT 'pending',
  confirmed_at     DATETIME NULL,
  created_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ord_account   FOREIGN KEY (account_id) REFERENCES platform_accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_ord_agreement FOREIGN KEY (agreement_id) REFERENCES order_agreements(id) ON DELETE SET NULL,
  CONSTRAINT fk_ord_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE SET NULL,
  CONSTRAINT fk_ord_creator   FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_ord_account (account_id, created_by, id),
  INDEX idx_ord_conversation (conversation_id),
  INDEX idx_ord_status (account_id, status, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_items (
  id            INT AUTO_INCREMENT PRIMARY KEY,
  order_id      INT NOT NULL,
  product_id    INT NULL,                                -- reference only; the rest are value snapshots
  name          VARCHAR(255) NOT NULL,
  variant_label VARCHAR(255) NULL,
  unit_price    DECIMAL(12,2) NULL,                      -- NULL = quote item
  quantity      INT NOT NULL DEFAULT 1,
  line_total    DECIMAL(12,2) NULL,
  CONSTRAINT fk_oi_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  INDEX idx_oi_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_discounts (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  order_id    INT NOT NULL,
  discount_id INT NULL,
  name        VARCHAR(255) NOT NULL,
  amount      DECIMAL(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT fk_od_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  INDEX idx_od_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS receipts (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  account_id      INT NOT NULL,
  created_by      INT NULL,                              -- owner (admins bypass)
  created_by_name VARCHAR(255) NULL,
  title           VARCHAR(255) NULL,
  s3_key          VARCHAR(512) NOT NULL,                 -- private S3 object, presigned on read
  content_type    VARCHAR(120) NULL,
  file_size       INT NULL,
  note            TEXT NULL,
  order_id        INT NULL,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_rcpt_account FOREIGN KEY (account_id) REFERENCES platform_accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_rcpt_creator FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_rcpt_order   FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
  INDEX idx_rcpt_account (account_id, created_by, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- page_stories — 24-hour Stories published to Facebook / Instagram (migration 057) --
-- One row per story per destination: publishing the same media to both platforms
-- creates two rows, each with its own status / platform id / expiry. Stories are
-- published DIRECTLY via the Graph API (not through the n8n post workflow): they
-- carry no caption, can't be scheduled on Meta's side, and expire after 24 hours
-- (expires_at = posted_at + 24h; the UI derives "expired" from it — status stays
-- 'posted'). Shared pool like post_pool: user_id records the creator (audit).
CREATE TABLE IF NOT EXISTS page_stories (
  id                INT AUTO_INCREMENT PRIMARY KEY,
  user_id           INT NULL,                    -- creator (audit; survives user deletion)
  account_id        INT NOT NULL,                -- the connected page it publishes through
  platform          VARCHAR(20) NOT NULL,        -- 'facebook' | 'instagram'
  media_type        VARCHAR(20) NOT NULL,        -- 'image' | 'video'
  s3_key            TEXT,                        -- private S3 object, presigned on read
  thumbnail_s3_key  TEXT,                        -- optimized still for grid previews
  status            VARCHAR(20) NOT NULL DEFAULT 'posting',
  platform_story_id VARCHAR(255) NULL,           -- FB story post id / IG media id
  failed_reason     TEXT,
  posted_at         DATETIME NULL,
  expires_at        DATETIME NULL,               -- posted_at + 24h
  created_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_page_stories_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_page_stories_account FOREIGN KEY (account_id) REFERENCES platform_accounts(id) ON DELETE CASCADE,
  CONSTRAINT chk_page_stories_platform CHECK (platform IN ('facebook','instagram')),
  CONSTRAINT chk_page_stories_media_type CHECK (media_type IN ('image','video')),
  CONSTRAINT chk_page_stories_status CHECK (status IN ('posting','posted','failed')),
  INDEX idx_page_stories_account (account_id, created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- conversation_surveys — customer satisfaction surveys (CSAT + NPS, migration 058) --
-- When an agent adds a note to a conversation (the "completed" signal), the server
-- rolls an admin-configured per-page chance (platform_accounts.survey_config) and may
-- email the customer a two-question survey: satisfaction with how the agent handled
-- the conversation (1-5) and likelihood to recommend the company (NPS 0-10). Sends
-- are SILENT — agents are never told a specific customer was surveyed; stats surface
-- only as day-lagged aggregates (today's sends appear tomorrow). The email comes from
-- the order / agreement linked to the conversation (Messenger's API exposes no email).
CREATE TABLE IF NOT EXISTS conversation_surveys (
  id              INT AUTO_INCREMENT PRIMARY KEY,
  token           CHAR(40) NOT NULL,               -- crypto-random hex; the public-link capability
  account_id      INT NOT NULL,                    -- page scope
  conversation_id INT NULL,                        -- thread that was rated (SET NULL keeps the stat)
  agent_user_id   INT NULL,                        -- agent whose handling is rated (snapshot at send)
  agent_name      VARCHAR(255) NULL,               -- durable display name
  customer_name   VARCHAR(255) NULL,
  email           VARCHAR(255) NOT NULL,
  email_source    VARCHAR(20) NOT NULL DEFAULT 'order',  -- 'order' | 'agreement' | 'test' (future: 'facebook')
  is_test         TINYINT(1) NOT NULL DEFAULT 0,   -- admin "send test survey" row (migration 059); excluded from analytics
  satisfaction    TINYINT NULL,                    -- 1-5: how the agent handled the conversation
  nps             TINYINT NULL,                    -- 0-10: would recommend the company
  comment         TEXT NULL,                       -- optional free-text feedback
  sent_at         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  responded_at    DATETIME NULL,
  expires_at      DATETIME NOT NULL,               -- link validity (sent_at + 7 days)
  CONSTRAINT fk_cs_account      FOREIGN KEY (account_id)      REFERENCES platform_accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_cs_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE SET NULL,
  CONSTRAINT fk_cs_agent        FOREIGN KEY (agent_user_id)   REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_cs_satisfaction CHECK (satisfaction IS NULL OR satisfaction BETWEEN 1 AND 5),
  CONSTRAINT chk_cs_nps          CHECK (nps IS NULL OR nps BETWEEN 0 AND 10),
  UNIQUE KEY uq_cs_token (token),
  INDEX idx_cs_account_sent (account_id, sent_at),
  INDEX idx_cs_conversation (conversation_id, sent_at),
  INDEX idx_cs_email (account_id, email, sent_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ---------------------------------------------------------------------------
-- Planner: plans, membership (roles) and goals (migrations 049 + 062)
-- A plan groups goals and carries its own membership. A user sees a plan only
-- if they're a member (admins bypass): viewer sees goals, editor edits goal
-- details, owner adds/deletes goals and manages the plan + members. Each goal
-- still tracks one page's metric as growth within [start_date, end_date].
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS planner_plans (
  id          INT AUTO_INCREMENT PRIMARY KEY,
  name        VARCHAR(255) NOT NULL,
  description VARCHAR(500) NULL,
  created_by  INT NULL,                         -- creator (audit); membership row holds the role
  created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_planner_plans_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS planner_plan_members (
  plan_id  INT NOT NULL,
  user_id  INT NOT NULL,
  role     VARCHAR(10) NOT NULL DEFAULT 'viewer',   -- viewer | editor | owner
  added_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (plan_id, user_id),
  CONSTRAINT fk_ppm_plan FOREIGN KEY (plan_id) REFERENCES planner_plans(id) ON DELETE CASCADE,
  CONSTRAINT fk_ppm_user FOREIGN KEY (user_id) REFERENCES users(id)         ON DELETE CASCADE,
  CONSTRAINT chk_ppm_role CHECK (role IN ('viewer','editor','owner')),
  INDEX idx_ppm_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS planner_goals (
  id             INT AUTO_INCREMENT PRIMARY KEY,
  account_id     INT NOT NULL,                 -- page the goal tracks
  plan_id        INT NULL,                     -- owning plan (migration 062)
  created_by     INT NULL,                     -- user who created it (audit)
  title          VARCHAR(255) NOT NULL,
  metric         VARCHAR(20)  NOT NULL,        -- see chk_planner_goals_metric
  period         VARCHAR(20)  NOT NULL,        -- daily|weekly|monthly|quarterly|yearly
  target_value   BIGINT       NOT NULL,
  baseline_value BIGINT       NULL,            -- follower count captured at creation (followers metric only)
  start_date     DATE NOT NULL,
  end_date       DATE NOT NULL,
  status         VARCHAR(20)  NOT NULL DEFAULT 'ongoing',  -- ongoing|completed|expired
  completed_at   DATETIME     NULL,
  created_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_planner_goals_account FOREIGN KEY (account_id) REFERENCES platform_accounts(id) ON DELETE CASCADE,
  CONSTRAINT fk_planner_goals_plan    FOREIGN KEY (plan_id)    REFERENCES planner_plans(id) ON DELETE CASCADE,
  CONSTRAINT fk_planner_goals_user    FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT chk_planner_goals_metric CHECK (metric IN ('followers','posts','comments','shares','views','reactions','sales','promoters','neutral','detractors')),
  CONSTRAINT chk_planner_goals_period CHECK (period IN ('daily','weekly','monthly','quarterly','yearly')),
  CONSTRAINT chk_planner_goals_status CHECK (status IN ('ongoing','completed','expired')),
  INDEX idx_planner_goals_account (account_id, status),
  INDEX idx_planner_goals_plan (plan_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
